const questions = [
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: 'function sayHi() {\n  console.log(name);\n  console.log(age);\n  var name = "Lydia";\n  let age = 21;\n}\n\nsayHi();',
    correctAnswer: 4,
    variants: [
      "`Lydia` et `undefined`",
      "`Lydia` et `ReferenceError`",
      "`ReferenceError` et `21`",
      "`undefined` et `ReferenceError`",
    ],
    explanation:
      "Dans la fonction, nous déclarons en premier la variable `name` grâce au mot clé `var`. Cela signifie que la variable est \"levée\" _(hoisted)_ (l'espace mémoire est définie à la phase de création) avec pour valeur par défaut `undefined`, jusqu'à ce que le script atteigne la ligne de définition de la variable. Nous n'avons pas encore défini la variable lorsque nous essayons d'afficher la variable `name`, donc elle a toujours la valeur `undefined`.\n\nLes variables avec le mot clé `let` (et `const`) sont \"levées\" _(hoisted)_, mais contrairement à `var`, elle n'est pas <i>initialisée</i>. Elles ne sont pas accessible avant la ligne qui les déclare (initialise). C'est appelé la \"zone morte temporaire\". Lorsque nous essayons d'accéder aux variables avant leur déclaration, JavaScript renvoie une `ReferenceError`.",
    id: 1,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: "for (var i = 0; i < 3; i++) {\n  setTimeout(() => console.log(i), 1);\n}\n\nfor (let i = 0; i < 3; i++) {\n  setTimeout(() => console.log(i), 1);\n}",
    correctAnswer: 3,
    variants: [
      "`0 1 2` et `0 1 2`",
      "`0 1 2` et `3 3 3`",
      "`3 3 3` et `0 1 2`",
    ],
    explanation:
      "À cause du système de queue dans JavaScript, la fonction de rappel _(callback)_ du `setTimeout` est appelée _après_ que la boucle soit exécutée. Comme la variable `i` dans la première boucle est déclarée avec le mot-clé `var`, c'est une variable globale. Pendant la boucle, nous incrémentons la valeur de `i` de `1` à chaque fois, en utilisant l'opérateur arithmétique `++`. Lorsque la fonction de rappel _(callback)_ du `setTimeout` est invoquée, `i` est égal à `3` dans le premier exemple.\n\nDans la seconde boucle, la variable `i` est déclarée avec le mot clé `let` : les variables déclarées avec `let` (et `const`) ont une portée de bloc (tout ce qui est entre `{ }` est considéré comme un bloc). Pendant chaque itération, `i` aura une nouvelle valeur, et chaque valeur sera définie dans la boucle.",
    id: 2,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: "const shape = {\n  radius: 10,\n  diameter() {\n    return this.radius * 2;\n  },\n  perimeter: () => 2 * Math.PI * this.radius\n};\n\nshape.diameter();\nshape.perimeter();",
    correctAnswer: 2,
    variants: [
      "`20` et `62.83185307179586`",
      "`20` et `NaN`",
      "`20` et `63`",
      "`NaN` et `63`",
    ],
    explanation:
      "Notez que la valeur de `diameter` est une fonction régulière, alors que celle de `perimeter` est une fonction fléchée.\n\nAvec les fonctions fléchée, le mot clé `this` réfère à son périmètre actuel, contrairement aux fonctions régulières ! Cela signifie que lorsque nous appelons `perimeter`, elle ne réfère pas à l'objet `shape`, mais à son périmètre actuel (`window` par exemple).\n\nIl n'y a pas de valeur `radius` dans cet objet, on retournera `undefined`.",
    id: 3,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: '+true;\n!"Lydia";',
    correctAnswer: 1,
    variants: ["`1` et `false`", "`false` et `NaN`", "`false` et `false`"],
    explanation:
      "L'opérateur arithmétique `+` essait de convertir un opérande en une valeur numérique. `true` devient `1`, et `false` devient `0`.\n\nLa chaîne de caractère `'Lydia'` est une valeur considérée comme vraie _(truthy)_. Ce que nous sommes actuellement en train de demander, c'est \"est-ce que cette valeur considérée comme vraie est fausse ?\". Ce qui retournera `false`.",
    id: 4,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Laquelle est vraie ?",
    code: 'const bird = {\n  size: "small"\n};\n\nconst mouse = {\n  name: "Mickey",\n  small: true\n};',
    correctAnswer: 1,
    variants: [
      "`mouse.bird.size` n'est pas valide",
      "`mouse[bird.size]` n'est pas valide",
      '`mouse[bird["size"]]` n\'est pas valide',
      "Toutes sont valides",
    ],
    explanation:
      "En JavaScript, toutes les clés d'objet sont des chaînes de caractères (sauf si c'est un Symbol). Bien que nous ne puissions pas les _typer_ comme des chaînes de caractères, elles sont converties en chaînes de caractères sous le capot.\n\nJavaScript interprète (ou décompresse) les instructions. Lorsque nous utilisons la notation par crochet, il voit le premier crochet `[` et continue jusqu'à ce qu'il trouve le crochet fermant `]`. Seulement après, il évalue l'instruction.\n\n`mouse[bird.size]` : Premièrement, il évalue `bird.size`, qui est `\"small\"`. `mouse[\"small\"]` retourne `true`.\n\nCependant, avec la notation par points, cela n'arrive pas. `mouse` n'a pas de clé appelée `bird`, ce qui signifie que `mouse.bird` est `undefined`. Puis, on demande `size` en utilisant la notation par point : `mouse.bird.size`. Comme `mouse.bird` est `undefined`, on demande `undefined.size`. Cela n'est pas valide, et nous aurons une erreur similaire à `Impossible de lire la propriété \"size\" de undefined`.",
    id: 5,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: 'let c = { greeting: "Hey!" };\nlet d;\n\nd = c;\nc.greeting = "Hello";\nconsole.log(d.greeting);',
    correctAnswer: 1,
    variants: [
      "`Hello`",
      "`Hey`",
      "`undefined`",
      "`ReferenceError`",
      "`TypeError`",
    ],
    explanation:
      'En JavaScript, tous les objets interagissent par _référence_ lorsqu\'on les définit égaux les uns aux autres.\n\nPremièrement, la variable `c` contaient une valeur d\'objet. Plus tard, nous assignons `d` avec la même référence que `c` à l\'objet.\n\n<img src="https://i.imgur.com/ko5k0fs.png" width="200">\n\nQuand on modifie un objet, on les modifie donc tous.',
    id: 6,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: "let a = 3;\nlet b = new Number(3);\nlet c = 3;\n\nconsole.log(a == b);\nconsole.log(a === b);\nconsole.log(b === c);",
    correctAnswer: 3,
    variants: [
      "`true` `false` `true`",
      "`false` `false` `true`",
      "`true` `false` `false`",
      "`false` `true` `true`",
    ],
    explanation:
      "`new Number()` est une fonction globale. Bien qu'il ressemble à un nombre, ce n'en est pas vraiment un : il a une poignée de fonctionnalités supplémentaire et est un objet.\n\nQuand nous utilisons l'opérateur `==`, il vérifie seulement qu'il s'agisse de la même _valeur_. Les deux ont pour valeur `3`, donc il retourne `true`.\n\nCependant, quand on utilise l'opérateur `===`, les 2 valeurs _et_ types doivent être les mêmes. `new Number()` n'est pas un nombre, c'est un **objet**, il retourne `false`.",
    id: 7,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: 'class Chameleon {\n  static colorChange(newColor) {\n    this.newColor = newColor;\n    return this.newColor;\n  }\n\n  constructor({ newColor = "green" } = {}) {\n    this.newColor = newColor;\n  }\n}\n\nconst freddie = new Chameleon({ newColor: "purple" });\nfreddie.colorChange("orange");',
    correctAnswer: 4,
    variants: ["`orange`", "`purple`", "`green`", "`TypeError`"],
    explanation:
      "La fonction `colorChange` est statique. Les méthodes statiques sont désignées pour vivre seulement dans le constructeur qui les a créé et ne peuvent pas être transférer aux enfants. Comme `freddie` est un enfant, la fonction n'est pas transférée et n'est pas disponible dans l'instance de `freddie` : une erreur `TypeError` est renvoyée.",
    id: 8,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: "let greeting;\ngreetign = {}; // Typo!\nconsole.log(greetign);",
    correctAnswer: 1,
    variants: [
      "`{}`",
      "`ReferenceError: greetign is not defined`",
      "`undefined`",
    ],
    explanation:
      "Il affiche l'objet, car on a juste créé un objet vide dans l'objet global ! Quand on écrit mal `greeting` en `greetign`, JavaScript l'interprète comme il le voit `global.greetign = {}` (ou `window.greetign = {}` dans le navigateur).\n\nPour éviter cela, on peut utiliser `\"use strict\"`. Cela nous assure de devoir déclarer la variable avant de lui assigner une valeur.",
    id: 9,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Que se passe-t-il lorsque nous faisons ça ?",
    code: 'function bark() {\n  console.log("Woof!");\n}\n\nbark.animal = "dog";',
    correctAnswer: 1,
    variants: [
      "Rien, c'est tout à fait bon !",
      "`SyntaxError`. Vous ne pouvez pas ajouter de propriétés à une fonction de cette façon.",
      "`undefined`",
      "`ReferenceError`",
    ],
    explanation:
      "C'est possible en JavaScript, car les fonctions sont des objets ! (Tout ce qui n'est pas de type primitif est un objet)\n\nUne fonction est un type spécial d'objet. Le code que vous écrivez vous-même n'est pas la fonction. La fonction est un objet avec des propriétés. Cette propriété est invocable.",
    id: 10,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: 'function Person(firstName, lastName) {\n  this.firstName = firstName;\n  this.lastName = lastName;\n}\n\nconst member = new Person("Lydia", "Hallie");\nPerson.getFullName = function() {\n  return `${this.firstName} ${this.lastName}`;\n};\n\nconsole.log(member.getFullName());\n```\n\n- A: `TypeError`\n- B: `SyntaxError`\n- C: `Lydia Hallie`\n- D: `undefined` `undefined`\n\n<details><summary><b>Réponse</b></summary>\n<p>\n\n#### Réponse : A\n\nVous ne pouvez pas ajouter de propriétés à un constructeur comme pour des objets normaux. Si vous voulez ajouter une fonctionnalité pour tous les objets en une fois, vous devez utiliser le prototype. Donc dans ce cas,\n\n```js\nPerson.prototype.getFullName = function() {\n  return `${this.firstName} ${this.lastName}`;\n};',
    correctAnswer: 1,
    variants: [
      "`TypeError`",
      "`SyntaxError`",
      "`Lydia Hallie`",
      "`undefined` `undefined`",
    ],
    explanation:
      "Vous ne pouvez pas ajouter de propriétés à un constructeur comme pour des objets normaux. Si vous voulez ajouter une fonctionnalité pour tous les objets en une fois, vous devez utiliser le prototype. Donc dans ce cas,\n\n```js\nPerson.prototype.getFullName = function() {\n  return `${this.firstName} ${this.lastName}`;\n};\n```\n\nrendra fonctionnel `member.getFullName`. Pourquoi est-ce bénéfique ? Disons que nous ajoutons cette méthode au constructeur directement. Peut-être que toutes les instances de `Person` n'ont pas besoin de cette méthode. Cela fera perdre de l'espace mémoire, car elles auront tous cette propriété, ce qui prendra de l'espace mémoire pour chaque instance. Alors que, si nous ajoutons la méthode au prototype uniquement, nous n'utilisons qu'un seul slot mémoire, et ils y auront tous accès !",
    id: 11,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: 'function Person(firstName, lastName) {\n  this.firstName = firstName;\n  this.lastName = lastName;\n}\n\nconst lydia = new Person("Lydia", "Hallie");\nconst sarah = Person("Sarah", "Smith");\n\nconsole.log(lydia);\nconsole.log(sarah);',
    correctAnswer: 1,
    variants: [
      '`Person {firstName: "Lydia", lastName: "Hallie"}` et `undefined`',
      '`Person {firstName: "Lydia", lastName: "Hallie"}` et `Person {firstName: "Sarah", lastName: "Smith"}`',
      '`Person {firstName: "Lydia", lastName: "Hallie"}` et `{}`',
    ],
    explanation:
      "Pour `sarah`, nous n'avons pas utilisé le mot clé `new`. Quand nous utilisons `new`, il fait référence à un nouvel objet vide que nous créons. Cependant, nous n'ajoutons pas `new`. Il réfère à **l'objet global** !\n\nNous disons que `this.firstName` est égal à `\"Sarah\"` et que `this.lastName` est égal à `Smith`. Ce que nous faisons c'est définir `global.firstName = 'Sarah'` et `global.lastName = 'Smith'`. La variable `sarah` elle-même reste à `undefined`.",
    id: 12,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle sont les trois phases de propagation des événements ?",
    code: null,
    correctAnswer: 4,
    variants: [
      "Target > Capturing > Bubbling",
      "Bubbling > Target > Capturing",
      "Target > Bubbling > Capturing",
      "Capturing > Target > Bubbling",
    ],
    explanation:
      "Durant la phase de **capture** _(capturing)_, l'événement passe par les éléments parents jusqu'à l'élément ciblé. Il atteint ensuite l'élément **ciblé** _(target)_, et commence à **bouillonner** _(bubbling)_.\n\n<img src=\"https://i.imgur.com/N18oRgd.png\" width=\"200\">",
    id: 13,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Tous les objets ont des prototypes.",
    code: null,
    correctAnswer: 2,
    variants: ["vrai", "faux"],
    explanation:
      "Tous les objets ont des prototypes, excepté pour les **objets standards**. Les objets standards ont accès à certaines méthodes et propriétés, comme `.toString`. C'est pour cette raison que vous pouvez utiliser les méthodes natives de JavaScript ! Toutes ces méthodes sont disponibles dans le prototype. Bien que JavaScript ne trouve pas la fonction dans l'objet, il parcourt le prototype et la méthode afin de la rendre accessible.",
    id: 14,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: 'function sum(a, b) {\n  return a + b;\n}\n\nsum(1, "2");',
    correctAnswer: 3,
    variants: ["`NaN`", "`TypeError`", '`"12"`', "`3`"],
    explanation:
      'JavaScript est un **langage à types dynamiques** : nous n\'avons pas besoin de spécifier le types des variables. Les valeurs peuvent être automatiquement converties vers les autres types sans que vous le sachiez, c\'est ce que l\'on appelle _la conversion de types implicites_ _(implicit type coercion)_.\n\nDans cette exemple, JavaScript convertit le nombre `1` en une chaîne de caractère, afin que la fonction ait du sens et puisse renvoyer une valeur. Durant l\'addition d\'un type numérique (`1`) et d\'un type chaîne de caractère (`\'2\'`), le nombre est traité comme une chaîne de caractère. Nous pouvons concaténer les chaînes de caractères comme `"Hello" + "World"`, c\'est donc ce qui arrive ici avec `"1" + "2"` qui retourne `"12"`.',
    id: 15,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: "let number = 0;\nconsole.log(number++);\nconsole.log(++number);\nconsole.log(number);",
    correctAnswer: 3,
    variants: ["`1` `1` `2`", "`1` `2` `2`", "`0` `2` `2`", "`0` `1` `2`"],
    explanation:
      "L'opérateur arithmétique **postfix** `++` :\n\n1. Retourne la valeur (ici il retourne `0`)\n2. Incrémente la valeur (le nombre est maintenant égal à `1`)\n\nL'opérateur arithmétique **préfix** `++` :\n\n1. Incrémente la valeur (le nombre est maintenant égal à `2`)\n2. Retourne la valeur (ici il retourne `2`)\n\nCela retourne donc `0 2 2`.",
    id: 16,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: 'function getPersonInfo(one, two, three) {\n  console.log(one);\n  console.log(two);\n  console.log(three);\n}\n\nconst person = "Lydia";\nconst age = 21;\n\ngetPersonInfo`${person} is ${age} years old`;',
    correctAnswer: 2,
    variants: [
      '`"Lydia"` `21` `["", " is ", " years old"]`',
      '`["", " is ", " years old"]` `"Lydia"` `21`',
      '`"Lydia"` `["", " is ", " years old"]` `21`',
    ],
    explanation:
      "Si vous utilisez les littéraux de gabarits, la valeur du premier argument sera toujours un tableau de valeurs des chaînes de caractère. Le reste des arguments seront les valeurs des expressions utilisées !",
    id: 17,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: 'function checkAge(data) {\n  if (data === { age: 18 }) {\n    console.log("Vous êtes un adulte !");\n  } else if (data == { age: 18 }) {\n    console.log("Vous êtes toujours un adulte.");\n  } else {\n    console.log(`Hmm.. Vous n\'avez pas l\'âge, je suppose.`);\n  }\n}\n\ncheckAge({ age: 18 });',
    correctAnswer: 3,
    variants: [
      "`Vous êtes un adulte !`",
      "`Vous êtes toujours un adulte.`",
      "`Hmm.. Vous n'avez pas l'âge, je suppose.`",
    ],
    explanation:
      "Lorsque l'on teste une égalité, les primitifs sont comparés par leur valeur, alors que les objets sont comparés par leur _référence_. JavaScript vérifie si les objets ont une référence à la même zone de la mémoire.=\n\nLes 2 objets que nous comparons n'ont pas ça : l'objet passé en paramètre fait référence à une zone mémoire différente que l'objet que nous utilisons pour faire la comparaison.\n\nC'est pourquoi les 2 conditions `{ age: 18 } === { age: 18 }` et `{ age: 18 } == { age: 18 }` retournent `false`.",
    id: 18,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: "function getAge(...args) {\n  console.log(typeof args);\n}\n\ngetAge(21);",
    correctAnswer: 3,
    variants: ['`"number"`', '`"array"`', '`"object"`', '`"NaN"`'],
    explanation:
      'La syntaxe des paramètres du reste _(rest parameters)_ (`...args`) retourne un tableau avec les arguments. Un tableau est un objet, donc `typeof args` retournera `"object"`.',
    id: 19,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: 'function getAge() {\n  "use strict";\n  age = 21;\n  console.log(age);\n}\n\ngetAge();',
    correctAnswer: 3,
    variants: ["`21`", "`undefined`", "`ReferenceError`", "`TypeError`"],
    explanation:
      'Avec `"use strict"`, vous pouvez êtes sûr de ne pas déclarer accidentellement des variables gloables. Nous ne déclarerons jamais la variable `age`, et temps que nous utiliserons `"use strict"`, cela créera une erreur de référence. Si nous n\'utilisons pas `"use strict"`, cela fonctionnera et la variable `age` sera attribué à l\'objet global.',
    id: 20,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la valeur de `sum` ?",
    code: 'const sum = eval("10*10+5");',
    correctAnswer: 1,
    variants: ["`105`", '`"105"`', "`TypeError`", '`"10*10+5"`'],
    explanation:
      "`eval` évalue les codes que nous passons en paramètre de type chaîne de caractères. Si c'est une expression, comme dans notre cas, il évaluera l'expression. L'expression est `10 * 10 + 5`, ce qui retourne le nombre `105`.",
    id: 21,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Pendant combien de temps `cool_secret` sera-t-il accessible ?",
    code: 'sessionStorage.setItem("cool_secret", 123);',
    correctAnswer: 2,
    variants: [
      "Pour toujours, les données ne seront pas perdues.",
      "Jusqu'à ce que l'utilisateur ferme l'onglet.",
      "Jusqu'à ce que l'utilisateur ferme son navigateur en entier, pas seulement son onglet.",
      "Jusqu'à ce que l'utilisateur éteindra son ordinateur.",
    ],
    explanation:
      "La donnée stockée dans le `sessionStorage` est supprimée après la fermeture de l'onglet.\n\nSi vous utilisez le `localStorage`, la donnée sera là pour toujours, jusqu'à ce que, par exemple, `localStorage.clear()` soit invoquée.",
    id: 22,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: "var num = 8;\nvar num = 10;\n\nconsole.log(num);",
    correctAnswer: 2,
    variants: ["`8`", "`10`", "`SyntaxError`", "`ReferenceError`"],
    explanation:
      "Avec le mot clé `var`, vous pouvez déclarer plusieurs variables avec le même nom. La variable aura pour valeur la dernière assignée.\n\nVous ne pouvez pas faire cela avec `let` ou `const` puisqu'ils ont une portée de bloc.",
    id: 23,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: 'const obj = { 1: "a", 2: "b", 3: "c" };\nconst set = new Set([1, 2, 3, 4, 5]);\n\nobj.hasOwnProperty("1");\nobj.hasOwnProperty(1);\nset.has("1");\nset.has(1);',
    correctAnswer: 3,
    variants: [
      "`false` `true` `false` `true`",
      "`false` `true` `true` `true`",
      "`true` `true` `false` `true`",
      "`true` `true` `true` `true`",
    ],
    explanation:
      "Toutes les clés d'objet (à l'exception des symboles) sont des chaînes de caractères sous le capot, même si vous ne les tapez pas vous-même en tant que chaîne. C'est pourquoi `obj.hasOwnProperty(\"1\")` renvoie également la valeur `true`.\n\nÇa ne marche pas comme ça pour un set. Il n'y a pas de `'1'` dans notre ensemble : `set.has('1')` renvoie `false`. Il a le type numérique `1`, `set.has(1)` renvoie `true`.",
    id: 24,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: 'const obj = { a: "un", b: "deux", a: "trois" };\nconsole.log(obj);',
    correctAnswer: 3,
    variants: [
      '`{ a: "un", b: "deux" }`',
      '`{ b: "deux", a: "trois" }`',
      '`{ a: "trois", b: "deux" }`',
      "`SyntaxError`",
    ],
    explanation:
      "Si vous avez deux clés portant le même nom, la clé sera remplacée. Elle sera toujours dans sa première position, mais avec la dernière valeur spécifiée.",
    id: 25,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question:
      "Le contexte global d'exécution de JavaScript crée 2 choses pour vous : l'objet global and le mot-clé `this`.",
    code: null,
    correctAnswer: 1,
    variants: ["Vrai", "Faux", "Ça dépend"],
    explanation:
      "Le contexte d'exécution de base est le contexte d'exécution global : c'est ce qui est accessible partout dans votre code.",
    id: 26,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: "for (let i = 1; i < 5; i++) {\n  if (i === 3) continue;\n  console.log(i);\n}",
    correctAnswer: 3,
    variants: ["`1` `2`", "`1` `2` `3`", "`1` `2` `4`", "`1` `3` `4`"],
    explanation:
      "L'instruction `continue` ignore une itération si une condition donnée renvoie `true`.",
    id: 27,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: 'String.prototype.giveLydiaPizza = () => {\n  return "Just give Lydia pizza already!";\n};\n\nconst name = "Lydia";\n\nname.giveLydiaPizza();',
    correctAnswer: 1,
    variants: [
      '`"Just give Lydia pizza already!"`',
      "`TypeError: not a function`",
      "`SyntaxError`",
      "`undefined`",
    ],
    explanation:
      "`String` est un constructeur intégré, auquel nous pouvons ajouter des propriétés. Je viens d'ajouter une méthode à son prototype. Les chaînes de caractère primitives sont automatiquement converties en un objet chaîne, généré par la fonction prototype de chaîne. Ainsi, toutes les chaînes (objets de chaîne) ont accès à cette méthode !",
    id: 28,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: 'const a = {};\nconst b = { key: "b" };\nconst c = { key: "c" };\n\na[b] = 123;\na[c] = 456;\n\nconsole.log(a[b]);',
    correctAnswer: 2,
    variants: ["`123`", "`456`", "`undefined`", "`ReferenceError`"],
    explanation:
      'Les clés d\'objet sont automatiquement converties en chaînes de caractères. Nous essayons de définir un objet en tant que clé de l\'objet `a`, avec la valeur `123`.\n\nCependant, lorsque nous transformons un objet en chaîne de caractère, il devient `"[Objet objet]"`. Donc, ce que nous disons ici, c\'est que un `a["Objet objet"] = 123`. Ensuite, nous pouvons essayer de refaire la même chose. `c` est un autre objet que nous sommes implicitement en train de transformer en chaîne de caractère. Donc, `a["Objet objet"] = 456`.\n\nEnsuite, nous affichons `a[b]`, qui est en fait `a["Objet objet"]`. Que nous venons de définir à `456`, nous renvoyons donc `456`.',
    id: 29,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: 'const foo = () => console.log("Premier");\nconst bar = () => setTimeout(() => console.log("Second"));\nconst baz = () => console.log("Troisième");\n\nbar();\nfoo();\nbaz();',
    correctAnswer: 2,
    variants: [
      "`Premier` `Second` `Troisième`",
      "`Premier` `Troisième` `Second`",
      "`Second` `Premier` `Troisième`",
      "`Second` `Troisième` `Premier`",
    ],
    explanation:
      'Nous avons une fonction `setTimeout` et nous l\'avons d\'abord appelée. Pourtant, il a été affiché en dernier.\n\nEn effet, dans les navigateurs, nous n’avons pas seulement le moteur d’exécution, nous avons aussi quelque chose appelé `WebAPI`. `WebAPI` nous donne la fonction` setTimeout` pour commencer, et par exemple le DOM.\n\nUne fois que la fonction de rappel _(callback)_ est poussée via la WebAPI, la fonction `setTimeout` elle-même (mais pas la fonction de rappel !) est extraite de la pile.\n\n<img src="https://i.imgur.com/X5wsHOg.png" width="200">\n\nMaintenant, `foo` est invoqué et `"Premier"` est affiché.\n\n<img src="https://i.imgur.com/Pvc0dGq.png" width="200">\n\n`foo` est extrait de la pile et `baz` est invoqué. `"Troisième"` est affiché.\n\n<img src="https://i.imgur.com/WhA2bCP.png" width="200">\n\nWebAPI ne peut simplement pas ajouter des éléments à la pile dès qu’elle est prête. Au lieu de cela, elle pousse la fonction de rappel vers quelque chose appelé la _file d\'attente_.\n\n<img src="https://i.imgur.com/NSnDZmU.png" width="200">\n\nC\'est ici qu\'une boucle d\'événement commence à fonctionner. La **boucle d\'événement** examine la pile et la file d\'attente des tâches. Si la pile est vide, il prend la première chose dans la file d\'attente et la pousse sur la pile.\n\n<img src="https://i.imgur.com/uyiScAI.png" width="200">\n\n`bar` est invoqué, `"Second"` est affiché et il est sorti de la pile.',
    id: 30,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question:
      "Quel est l'élément ciblé _(event.target)_ au clic sur le bouton _(button)_ ?",
    code: null,
    correctAnswer: 3,
    variants: [
      "La `div` extérieure",
      "La `div` intérieure",
      "`button`",
      "Un tableau de tous les éléments imbriqués.",
    ],
    explanation:
      "L'élément imbriqué le plus profond qui a provoqué l'événement est la cible de l'événement. Vous pouvez arrêter le bouillonnement _(bubbling)_ en utilisant `event.stopPropagation`.",
    id: 31,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quand vous cliquez sur le paragraphe, quelle est la sortie ?",
    code: null,
    correctAnswer: 1,
    variants: ["`p` `div`", "`div` `p`", "`p`", "`div`"],
    explanation:
      "Si nous cliquons sur `p`, nous verrons deux lignes : `p` et `div`. Lors de la propagation d'un événement, il y a 3 phases: capture, cible et bouillonnement _(bubbling)_. Par défaut, les gestionnaires d'événements sont exécutés dans la phase de bouillonnement (sauf si vous définissez `useCapture` sur` true`). Il va de l'élément imbriqué le plus profond vers l'extérieur.",
    id: 32,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: 'const person = { name: "Lydia" };\n\nfunction sayHi(age) {\n  console.log(`${this.name} is ${age}`);\n}\n\nsayHi.call(person, 21);\nsayHi.bind(person, 21);',
    correctAnswer: 4,
    variants: [
      "`undefined is 21` `Lydia is 21`",
      "`function` `function`",
      "`Lydia is 21` `Lydia is 21`",
      "`Lydia is 21` `function`",
    ],
    explanation:
      "Avec les deux, nous pouvons transmettre l'objet auquel nous voulons que le mot clé `this` fasse référence. Cependant, `.call` est aussi _exécuté immédiatement_ !\n\n`.bind.` renvoie une copie de la fonction, mais avec un contexte lié ! Elle n'est pas exécutée immédiatement.",
    id: 33,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: "function sayHi() {\n  return (() => 0)();\n}\n\ntypeof sayHi();",
    correctAnswer: 2,
    variants: ['`"object"`', '`"number"`', '`"function"`', '`"undefined"`'],
    explanation:
      'La fonction `sayHi` renvoie la valeur renvoyée par la fonction immédiatement appelée (IIFE). Cette fonction a renvoyé `0`, qui est du type `"nombre"`.\n\nPour info : il n\'y a que 7 types natifs : `null`, `undefined`, `boolean`, `number`, `string`, `object`, `symbol` et `bigint`. `"function"` n\'est pas un type, puisque les fonctions sont des objets, il est de type `"object"`.',
    id: 34,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Lesquelles de ces valeurs sont fausses ?",
    code: '0;\nnew Number(0);\n("");\n(" ");\nnew Boolean(false);\nundefined;',
    correctAnswer: 1,
    variants: [
      "`0`, `''`, `undefined`",
      "`0`, `new Number(0)`, `''`, `new Boolean(false)`, `undefined`",
      "`0`, `''`, `new Boolean(false)`, `undefined`",
      "Toutes sont fausses",
    ],
    explanation:
      "Il n'y a que six valeurs de fausses :\n\n- `undefined`\n- `null`\n- `NaN`\n- `0`\n- `''` (chaîne de caractère vide)\n- `false`\n\nLes constructeurs de fonctions, comme `new Number` et `new Boolean` sont la vraies.",
    id: 35,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: "console.log(typeof typeof 1);",
    correctAnswer: 2,
    variants: ['`"number"`', '`"string"`', '`"object"`', '`"undefined"`'],
    explanation:
      '`typeof 1` retourne `"number"`.\n`typeof "number"` retourne `"string"`',
    id: 36,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: "const numbers = [1, 2, 3];\nnumbers[10] = 11;\nconsole.log(numbers);",
    correctAnswer: 3,
    variants: [
      "`[1, 2, 3, 7 x null, 11]`",
      "`[1, 2, 3, 11]`",
      "`[1, 2, 3, 7 x empty, 11]`",
      "`SyntaxError`",
    ],
    explanation:
      "Lorsque vous définissez une valeur sur un élément d'un tableau qui dépasse la longueur du tableau, JavaScript crée un quelque chose appelé \"emplacements vides\". Ceux-ci ont en fait la valeur `undefined`, mais vous verrez quelque chose comme :\n\n`[1, 2, 3, 7 x empty, 11]`\n\nen fonction de l'endroit où vous l'exécutez (différent pour chaque navigateur, nœud, etc.).",
    id: 37,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: "(() => {\n  let x, y;\n  try {\n    throw new Error();\n  } catch (x) {\n    (x = 1), (y = 2);\n    console.log(x);\n  }\n  console.log(x);\n  console.log(y);\n})();",
    correctAnswer: 1,
    variants: [
      "`1` `undefined` `2`",
      "`undefined` `undefined` `undefined`",
      "`1` `1` `2`",
      "`1` `undefined` `undefined`",
    ],
    explanation:
      "Le bloc `catch` reçoit l'argument `x`. Ce n'est pas le même `x` que la variable que nous passons en arguments. Cette variable `x` a une portée de bloc.\n\nPlus tard, nous définissons cette variable de bloc égale à `1` et définissons la valeur de la variable `y`. Maintenant, nous affichons la variable `x` de portée de bloc, dont la valeur est égale à `1`.\n\nEn dehors du bloc `catch`, `x` est toujours `undefined` et `y` est égal à `2`. Lorsque nous voulons `console.log(x)` en dehors du bloc `catch`, il renvoie `undefined`, et `y` renvoie `2`.",
    id: 38,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Tout en JavaScript est...",
    code: null,
    correctAnswer: 1,
    variants: [
      "primitif ou objet",
      "fonction ou objet",
      "question délicate ! Seulement des objets",
      "nombre ou objet",
    ],
    explanation:
      "JavaScript n'a que des types et des objets primitifs.\n\nLes types primitifs sont `boolean`, `null`, `undefined`, `bigint`, `number`, `string` et `symbol`.\n\nCe qui différencie une primitive d'un objet, c'est que les primitives n'ont aucune propriété ou méthode. Cependant, vous remarquerez que  `'foo'.toUpperCase()` est évalué à `'FOO'` et n'entraîne pas de `TypeError`. En effet, lorsque vous essayez d'accéder à une propriété ou à une méthode sur une primitive telle qu'une chaîne, JavaScript encapsule implicitement l'objet à l'aide de l'une des classes d'encapsulation, à savoir `String`, puis supprime immédiatement l'encapsulation après l'évaluation de l'expression. Toutes les primitives à l'exception de `null` et` undefined` présentent ce comportement.",
    id: 39,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: "[[0, 1], [2, 3]].reduce(\n  (acc, cur) => {\n    return acc.concat(cur);\n  },\n  [1, 2]\n);",
    correctAnswer: 3,
    variants: [
      "`[0, 1, 2, 3, 1, 2]`",
      "`[6, 1, 2]`",
      "`[1, 2, 0, 1, 2, 3]`",
      "`[1, 2, 6]`",
    ],
    explanation:
      "`[1, 2]` est notre valeur initiale. C'est la valeur avec laquelle nous commençons et la valeur du tout premier `acc`. Au premier tour, `acc` est `[1,2]` et `cur` est `[0, 1]`. Nous les concaténons, ce qui donne `[1, 2, 0, 1]`.\n\nEnsuite, `acc` est `[1, 2, 0, 1]` et `cur` est `[2, 3]`. Nous les concaténons et obtenons `[1, 2, 0, 1, 2, 3]`",
    id: 40,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: '!!null;\n!!"";\n!!1;',
    correctAnswer: 2,
    variants: [
      "`false` `true` `false`",
      "`false` `false` `true`",
      "`false` `true` `true`",
      "`true` `true` `false`",
    ],
    explanation:
      '`null` est faux. `!null` retourne `true`. `!true` retourne `false`.\n\n`""` est faux. `!""` retourne `true`. `!true` retourne `false`.\n\n`1` est vrai. `!1` retourne `false`. `!false` retourne `true`.',
    id: 41,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Que retourne la méthode `setInterval` ?",
    code: 'setInterval(() => console.log("Hi"), 1000);',
    correctAnswer: 1,
    variants: [
      "un identifiant unique",
      "le temps de millisecondes spécifié",
      "la fonction passée en paramètre",
      "`undefined`",
    ],
    explanation:
      "Il retourne un identifiant unique. Cet identifiant peut être utilisé pour effacer cet interval avec la fonction `clearInterval()`.",
    id: 42,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Que retourne ceci ?",
    code: '[..."Lydia"];',
    correctAnswer: 1,
    variants: [
      '`["L", "y", "d", "i", "a"]`',
      '`["Lydia"]`',
      '`[[], "Lydia"]`',
      '`[["L", "y", "d", "i", "a"]]`',
    ],
    explanation:
      "Une chaîne de caractère est itérable. L'opérateur de déconstruction transforme chaque caractère d'un itérable en un élément.",
    id: 43,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: "function* generator(i) {\n  yield i;\n  yield i * 2;\n}\n\nconst gen = generator(10);\n\nconsole.log(gen.next().value);\nconsole.log(gen.next().value);",
    correctAnswer: 3,
    variants: [
      "`[0, 10], [10, 20]`",
      "`20, 20`",
      "`10, 20`",
      "`0, 10 and 10, 20`",
    ],
    explanation:
      'Les fonctions régulières ne peuvent pas être arrêtées à mi-parcours après l\'invocation. Cependant, une fonction de générateur peut être "arrêtée" à mi-chemin et continuer plus tard à partir de son point d\'arrêt. Chaque fois qu\'une fonction génératrice rencontre un mot-clé `yield`, elle renvoie la valeur spécifiée après celui-ci. Notez que la fonction du générateur dans ce cas ne _return_ pas la valeur, il _yields_ la valeur.\n\nPremièrement, nous initialisons la fonction du générateur avec `i` égal à` 10`. Nous appelons la fonction génératrice en utilisant la méthode `next()`. La première fois que nous appelons la fonction de générateur, `i` est égal à `10`. Il rencontre le premier mot-clé `yield` : il donne la valeur de `i`. Le générateur est maintenant "en pause" et `10` est affiché.\n\nEnsuite, nous appelons à nouveau la fonction avec la méthode `next()`. Il commence à continuer là où il s’était arrêté précédemment, toujours avec `i` égal à `10`. Maintenant, il rencontre le prochain mot-clé `yield` et donne `i * 2`. `i` est égal à `10`, donc il renvoie `10 * 2`, ce qui correspond à `20`. Cela donne `10, 20`.',
    id: 44,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Qu'est-ce que cela retourne ?",
    code: 'const firstPromise = new Promise((res, rej) => {\n  setTimeout(res, 500, "one");\n});\n\nconst secondPromise = new Promise((res, rej) => {\n  setTimeout(res, 100, "two");\n});\n\nPromise.race([firstPromise, secondPromise]).then(res => console.log(res));',
    correctAnswer: 2,
    variants: ['`"one"`', '`"two"`', '`"two" "one"`', '`"one" "two"`'],
    explanation:
      "Lorsque nous passons plusieurs promesses à la méthode `Promise.race`, elle résout/rejette la promesse _first_ qui résout/rejette. Nous passons, à la méthode `setTimeout`, un timer: 500 ms pour la première promesse (`firstPromise`), et 100 ms pour la deuxième promesse (`secondPromise`). Cela signifie que le `secondPromise` se résout en premier avec la valeur de `'two'`. `res` contient maintenant la valeur de `'deux'`, qui est affiché.",
    id: 45,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: 'let person = { name: "Lydia" };\nconst members = [person];\nperson = null;\n\nconsole.log(members);',
    correctAnswer: 4,
    variants: ["`null`", "`[null]`", "`[{}]`", '`[{ name: "Lydia" }]`'],
    explanation:
      'Tout d\'abord, nous déclarons une variable `person` avec la valeur d\'un objet possédant une propriété `name`.\n\n<img src="https://i.imgur.com/TML1MbS.png" width="200">\n\nEnsuite, nous déclarons une variable appelée `membres`. Nous définissons le premier élément de ce tableau égal à la valeur de la variable `person`. Les objets interagissent par référence quand ils sont égaux. Lorsque vous affectez une référence d\'une variable à une autre, vous créez une copie de cette référence. (notez qu\'ils n\'ont pas la même référence !)\n\n<img src="https://i.imgur.com/FSG5K3F.png" width="300">\n\nEnsuite, nous définissons la variable `person` égale à `null`.\n\n<img src="https://i.imgur.com/sYjcsMT.png" width="300">\n\nNous modifions seulement la valeur de la variable `person`, et non le premier élément du tableau, car cet élément a une référence (copiée) différente de l\'objet. Le premier élément de `members` conserve sa référence à l\'objet d\'origine. Lorsque nous affichons le tableau `members`, le premier élément contient toujours la valeur de l\'objet, qui est affiché.',
    id: 46,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: 'const person = {\n  name: "Lydia",\n  age: 21\n};\n\nfor (const item in person) {\n  console.log(item);\n}',
    correctAnswer: 2,
    variants: [
      '`{ name: "Lydia" }, { age: 21 }`',
      '`"name", "age"`',
      '`"Lydia", 21`',
      '`["name", "Lydia"], ["age", 21]`',
    ],
    explanation:
      "Avec une boucle `for-in`, nous pouvons parcourir les clés d'objet, dans ce cas `name` et `age`. Sous le capot, les clés d'objet sont des chaînes (si elles ne sont pas un symbole). A chaque boucle, nous définissons la valeur de `item` égal à la clé courante sur laquelle elle est entrain d'itéré. Premièrement, `item` est égal à `name` et est affiché. Ensuite, `item` est égal à `age`, qui est affiché.",
    id: 47,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: 'console.log(3 + 4 + "5");',
    correctAnswer: 2,
    variants: ['`"345"`', '`"75"`', "`12`", '`"12"`'],
    explanation:
      "L'associativité des opérateurs correspond à l'ordre dans lequel le compilateur évalue les expressions, de gauche à droite ou de droite à gauche. Cela se produit uniquement si tous les opérateurs ont la même priorité. Nous n'avons qu'un type d'opérateur : `+`. De plus, l'associativité est de gauche à droite.\n\n`3 + 4` est évalué en premier. Cela donne le nombre `7`.\n\n`7 + '5'` donne `'75'` à cause de la conversion. JavaScript convertit le nombre `7` en une chaîne, voir question 15. Nous pouvons concaténer deux chaînes en utilisant l'opérateur `+`. `\"7\" + \"5\"` a pour résultat `\"75\"`.",
    id: 48,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la valeur de `num` ?",
    code: 'const num = parseInt("7*6", 10);',
    correctAnswer: 3,
    variants: ["`42`", '`"42"`', "`7`", "`NaN`"],
    explanation:
      "Seuls les premiers nombres de la chaîne sont renvoyés. Basé sur la base dix (le deuxième argument permettant de spécifier le type de nombre que nous voulons analyser: base 10, hexadécimal, octal, binaire, etc.), `parseInt` vérifie si les caractères de la chaîne sont valides. Une fois qu'il rencontre un caractère qui n'est pas un nombre valide dans la base, il arrête l'analyse et ignore les caractères suivants.\n\n`*` n'est pas un nombre valide. Il analyse seulement `7` dans la décimale `7`. `num` contient maintenant la valeur de` 7`.",
    id: 49,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: '[1, 2, 3].map(num => {\n  if (typeof num === "number") return;\n  return num * 2;\n});',
    correctAnswer: 3,
    variants: [
      "`[]`",
      "`[null, null, null]`",
      "`[undefined, undefined, undefined]`",
      "`[ 3 x empty ]`",
    ],
    explanation:
      "Lors du l'utilisation de `map` sur le tableau, la valeur de `num` est égale à l’élément sur lequel elle est en train de boucler. Dans ce cas, les éléments sont des nombres. La condition de l'instruction si `typeof num === \"numéro\"` renvoie `true`. La fonction map crée un nouveau tableau et insère les valeurs renvoyées par la fonction.\n\nCependant, nous ne renvoyons pas de valeur. Lorsque nous ne renvoyons pas de valeur à partir de la fonction, la fonction renvoie `undefined`. Le bloc de fonction est appelé pour chaque élément du tableau. Ainsi, pour chaque élément, nous renvoyons `undefined`.",
    id: 50,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: 'function getInfo(member, year) {\n  member.name = "Lydia";\n  year = "1998";\n}\n\nconst person = { name: "Sarah" };\nconst birthYear = "1997";\n\ngetInfo(person, birthYear);\n\nconsole.log(person, birthYear);',
    correctAnswer: 1,
    variants: [
      '`{ name: "Lydia" }, "1997"`',
      '`{ name: "Sarah" }, "1998"`',
      '`{ name: "Lydia" }, "1998"`',
      '`{ name: "Sarah" }, "1997"`',
    ],
    explanation:
      'Les arguments sont passés par _valeur_, à moins que leur valeur ne soit un objet, ils sont passés par _référence_. `birthYear` est passée par valeur, car c\'est une chaîne, pas un objet. Lorsque nous passons des arguments par valeur, une copie de cette valeur est créée (voir question 46).\n\nLa variable `birthYear` a une référence à la valeur `"1997"`. L\'argument `year` fait également référence à la valeur `"1997"`, mais il ne s\'agit pas de la même valeur que celle de `birthYear`. Lorsque nous mettons à jour la valeur de `year` en plaçant `year` égal à `"1998"`, nous ne mettons à jour que la valeur de `year`. `birthYear` est toujours égal à `"1997"`.\n\nLa valeur de `person` est un objet. L\'argument `membre` a une référence (copiée) au même objet. Lorsque nous modifions une propriété de l\'objet, `membre` a une référence à la valeur de` person` sera également modifiée, puisqu\'elles ont toutes les deux une référence au même objet. La propriété `name` de `person` est maintenant égale à la valeur `"Lydia"`.',
    id: 51,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: 'function greeting() {\n  throw "Hello world!";\n}\n\nfunction sayHi() {\n  try {\n    const data = greeting();\n    console.log("It worked!", data);\n  } catch (e) {\n    console.log("Oh no an error!", e);\n  }\n}\n\nsayHi();',
    correctAnswer: 4,
    variants: [
      '`"It worked! Hello world!"`',
      '`"Oh no an error: undefined`',
      "`SyntaxError: can only throw Error objects`",
      '`"Oh no an error: Hello world!`',
    ],
    explanation:
      "Avec l'instruction `throw`, nous pouvons créer des erreurs personnalisées. Avec cette déclaration, vous pouvez lancer des exceptions. Une exception peut être une <b>chaîne</b>, un <b>numéro</b>, un <b>booléen</b> ou un <b>objet</b>. Dans ce cas, notre exception est la chaîne `'Hello world'`.\n\nAvec l'instruction `catch`, nous pouvons spécifier quoi faire si une exception est levée dans le bloc `try`. Une exception est levée : la chaîne `'Hello world'`. `e` est maintenant égal à cette chaîne, que nous affichons. Il en résulte `'Oh an error: Hello world'`.",
    id: 52,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: 'function Car() {\n  this.make = "Lamborghini";\n  return { make: "Maserati" };\n}\n\nconst myCar = new Car();\nconsole.log(myCar.make);',
    correctAnswer: 2,
    variants: [
      '`"Lamborghini"`',
      '`"Maserati"`',
      "`ReferenceError`",
      "`TypeError`",
    ],
    explanation:
      'Lorsque vous retournez une propriété, la valeur de la propriété est égale à la valeur _retournée_ et non à la valeur définie dans la fonction constructeur. Nous renvoyons la chaîne `"Maserati"`, donc `myCar.make` est égal à `"Maserati"`.',
    id: 53,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: '(() => {\n  let x = (y = 10);\n})();\n\nconsole.log(typeof x);\nconsole.log(typeof y);\n```\n\n- A: `"undefined", "number"`\n- B: `"number", "number"`\n- C: `"object", "number"`\n- D: `"number", "undefined"`\n\n<details><summary><b>Réponse</b></summary>\n<p>\n\n#### Réponse : A\n\n`let x = y = 10;` est en réalité un raccourci pour :\n\n```javascript\ny = 10;\nlet x = y;',
    correctAnswer: 1,
    variants: [
      '`"undefined", "number"`',
      '`"number", "number"`',
      '`"object", "number"`',
      '`"number", "undefined"`',
    ],
    explanation:
      "`let x = y = 10;` est en réalité un raccourci pour :\n\n```javascript\ny = 10;\nlet x = y;\n```\n\nLorsque nous définissons `y` égal à `10`, nous ajoutons en fait une propriété `y` à l'objet global (`window` dans le navigateur,` global` dans NodeJS). Dans un navigateur, `window.y` est égal à `10`.\n\nEnsuite, nous déclarons une variable `x` avec la valeur de `y`, qui est `10`. Les variables déclarées avec le mot-clé `let` ont une portée de bloc, elles ne sont définies que dans le bloc dans lequel elles sont déclarées; la fonction immédiatement invoquée (IIFE) dans ce cas. Lorsque nous utilisons l'opérateur `typeof`, l'opérande `x` n'est pas défini: nous essayons d'accéder à `x` en dehors du bloc dans lequel il est déclaré. Cela signifie que `x` n'est pas défini. Les valeurs auxquelles aucune valeur n'a été attribuée ni déclarée sont du type `\"undefined\"`. `console.log (typeof x)` renvoie `\"undefined\"`.\n\nCependant, nous avons créé une variable globale `y` lorsque `y` est égal à `10`. Cette valeur est accessible n'importe où dans notre code. `y` est défini et contient une valeur de type `\"number\"`. `console.log (typeof y)` renvoie `\"number\"`.",
    id: 54,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: 'class Dog {\n  constructor(name) {\n    this.name = name;\n  }\n}\n\nDog.prototype.bark = function() {\n  console.log(`Woof I am ${this.name}`);\n};\n\nconst pet = new Dog("Mara");\n\npet.bark();\n\ndelete Dog.prototype.bark;\n\npet.bark();',
    correctAnswer: 1,
    variants: [
      '`"Woof I am Mara"`, `TypeError`',
      '`"Woof I am Mara"`,`"Woof I am Mara"`',
      '`"Woof I am Mara"`, `undefined`',
      "`TypeError`, `TypeError`",
    ],
    explanation:
      "Nous pouvons supprimer des propriétés d'objets en utilisant le mot-clé `delete`, également dans le prototype. En supprimant une propriété dans le prototype, elle n’est plus disponible dans la chaîne de prototypes. Dans ce cas, la fonction `bark` n'est plus disponible dans le prototype après `delete Dog.prototype.bark`, mais nous essayons toujours d'y accéder.\n\nLorsque nous essayons d'appeler quelque chose qui n'est pas une fonction, un `TypeError` est levé. Dans ce cas, `TypeError: pet.bark n'est pas une fonction`, puisque` pet.bark` est `undefined`.",
    id: 55,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: "const set = new Set([1, 1, 2, 3, 4]);\n\nconsole.log(set);",
    correctAnswer: 4,
    variants: [
      "`[1, 1, 2, 3, 4]`",
      "`[1, 2, 3, 4]`",
      "`{1, 1, 2, 3, 4}`",
      "`{1, 2, 3, 4}`",
    ],
    explanation:
      "L'objet `Set` est une collection de valeurs _uniques_ : une valeur ne peut apparaître qu'une seule fois dans un ensemble.\n\nNous avons passé l'itérable `[1, 1, 2, 3, 4]` avec une valeur dupliquée `1`. Puisque nous ne pouvons pas avoir deux valeurs identiques dans un ensemble, l'une d'entre elles est supprimée. Cela donne `{1, 2, 3, 4}`.",
    id: 56,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: '// counter.js\nlet counter = 10;\nexport default counter;\n```\n\n```javascript\n// index.js\nimport myCounter from "./counter";\n\nmyCounter += 1;\n\nconsole.log(myCounter);',
    correctAnswer: 3,
    variants: ["`10`", "`11`", "`Error`", "`NaN`"],
    explanation:
      "Un module importé est _en lecture seule_ : vous ne pouvez pas modifier le module importé. Seul le module qui les exporte peut en changer la valeur.\n\nLorsque nous essayons d'incrémenter la valeur de `myCounter`, une erreur est générée : `myCounter` est en lecture seule et ne peut pas être modifié.",
    id: 57,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: 'const name = "Lydia";\nage = 21;\n\nconsole.log(delete name);\nconsole.log(delete age);',
    correctAnswer: 1,
    variants: [
      "`false`, `true`",
      '`"Lydia"`, `21`',
      "`true`, `true`",
      "`undefined`, `undefined`",
    ],
    explanation:
      "L'opérateur `delete` renvoie une valeur booléenne : `true` en cas de suppression réussie, sinon il renvoie `false`. Toutefois, les variables déclarées avec les mots clés `var`,` const` ou `let` ne peuvent pas être supprimées à l'aide de l'opérateur` delete`.\n\nLa variable `name` a été déclarée avec un mot-clé `const`. Par conséquent, sa suppression a échoué : `false` est renvoyé. Lorsque nous définissons `age` égal à `21`, nous avons en fait ajouté une propriété appelée `age` à l'objet global. De cette façon, vous pouvez supprimer des propriétés d’objets, ainsi que de l’objet global, pour que `delete age` renvoie` true`.",
    id: 58,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: 'const numbers = [1, 2, 3, 4, 5];\nconst [y] = numbers;\n\nconsole.log(y);\n```\n\n- A: `[[1, 2, 3, 4, 5]]`\n- B: `[1, 2, 3, 4, 5]`\n- C: `1`\n- D: `[1]`\n\n<details><summary><b>Réponse</b></summary>\n<p>\n\n#### Réponse : C\n\nNous pouvons décompresser les valeurs des tableaux ou les propriétés des objets en les détruisant. Par exemple :\n\n```javascript\n[a, b] = [1, 2];\n```\n\n<img src="https://i.imgur.com/ADFpVop.png" width="200">\n\nLa valeur de `a` est maintenant `1` et la valeur de `b` est maintenant `2`. Ce que nous avons réellement fait dans la question, c\'est :\n\n```javascript\n[y] = [1, 2, 3, 4, 5];',
    correctAnswer: 3,
    variants: ["`[[1, 2, 3, 4, 5]]`", "`[1, 2, 3, 4, 5]`", "`1`", "`[1]`"],
    explanation:
      'Nous pouvons décompresser les valeurs des tableaux ou les propriétés des objets en les détruisant. Par exemple :\n\n```javascript\n[a, b] = [1, 2];\n```\n\n<img src="https://i.imgur.com/ADFpVop.png" width="200">\n\nLa valeur de `a` est maintenant `1` et la valeur de `b` est maintenant `2`. Ce que nous avons réellement fait dans la question, c\'est :\n\n```javascript\n[y] = [1, 2, 3, 4, 5];\n```\n\n<img src="https://i.imgur.com/NzGkMNk.png" width="200">\n\nCela signifie que la valeur de `y` est égale à la première valeur du tableau, qui correspond au nombre `1`. Lorsque nous affichons `y`,` 1` est renvoyé.',
    id: 59,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: 'const user = { name: "Lydia", age: 21 };\nconst admin = { admin: true, ...user };\n\nconsole.log(admin);',
    correctAnswer: 2,
    variants: [
      '`{ admin: true, user: { name: "Lydia", age: 21 } }`',
      '`{ admin: true, name: "Lydia", age: 21 }`',
      '`{ admin: true, user: ["Lydia", 21] }`',
      "`{ admin: true }`",
    ],
    explanation:
      "Il est possible de combiner des objets en utilisant l'opérateur de déconstruction `...`. Il vous permet de créer des copies des paires clé / valeur d'un objet et de les ajouter à un autre objet. Dans ce cas, nous créons des copies de l'objet `user` et nous les ajoutons à l'objet` admin`. L'objet `admin` contient maintenant les paires clé / valeur copiées, ce qui donne `{admin: true, nom: \"Lydia\", age: 21}`.",
    id: 60,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: 'const person = { name: "Lydia" };\n\nObject.defineProperty(person, "age", { value: 21 });\n\nconsole.log(person);\nconsole.log(Object.keys(person));',
    correctAnswer: 2,
    variants: [
      '`{ name: "Lydia", age: 21 }`, `["name", "age"]`',
      '`{ name: "Lydia", age: 21 }`, `["name"]`',
      '`{ name: "Lydia"}`, `["name", "age"]`',
      '`{ name: "Lydia"}`, `["age"]`',
    ],
    explanation:
      "Avec la méthode `defineProperty`, nous pouvons ajouter de nouvelles propriétés à un objet ou modifier celles existantes. Lorsque nous ajoutons une propriété à un objet en utilisant la méthode `defineProperty`, il s’agit par défaut d'une propriété _non énumérable_. La méthode `Object.keys` renvoie tous les noms de propriétés _énumérable_ à partir d'un objet, dans ce cas uniquement `\"name\"`.\n\nLes propriétés ajoutées à l'aide de la méthode `defineProperty` sont immuables par défaut. Vous pouvez remplacer ce comportement en utilisant les propriétés `writeable`, `configurable` et `enumerable`. De cette façon, la méthode `defineProperty` vous donne beaucoup plus de contrôle sur les propriétés que vous ajoutez à un objet.",
    id: 61,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: 'const settings = {\n  username: "lydiahallie",\n  level: 19,\n  health: 90\n};\n\nconst data = JSON.stringify(settings, ["level", "health"]);\nconsole.log(data);',
    correctAnswer: 1,
    variants: [
      '`"{"level":19, "health":90}"`',
      '`"{"username": "lydiahallie"}"`',
      '`"["level", "health"]"`',
      '`"{"username": "lydiahallie", "level":19, "health":90}"`',
    ],
    explanation:
      'Le second argument de `JSON.stringify` est le _replaçant_. Le remplaçant peut être une fonction ou un tableau, et vous permet de contrôler quoi et comment les valeurs doivent être stringifiées.\n\nSi le remplaçant est un _tableau_, seules les propriétés dont les noms sont inclus dans le tableau seront ajoutées à la chaîne JSON. Dans ce cas, seules les propriétés avec les noms `"level"` et `"health"` sont incluses, `"username"` est exclu. `data` est maintenant égal à `"{"level":19, "health":90}"`.\n\nSi le remplaçant est une _fonction_, cette fonction est appelée sur chaque propriété de l\'objet que vous personnalisez. La valeur renvoyée par cette fonction sera la valeur de la propriété lorsqu\'elle sera ajoutée à la chaîne JSON. Si la valeur est `undefined`, cette propriété est exclue de la chaîne JSON.',
    id: 62,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie ?",
    code: "let num = 10;\n\nconst increaseNumber = () => num++;\nconst increasePassedNumber = number => number++;\n\nconst num1 = increaseNumber();\nconst num2 = increasePassedNumber(num1);\n\nconsole.log(num1);\nconsole.log(num2);",
    correctAnswer: 1,
    variants: ["`10`, `10`", "`10`, `11`", "`11`, `11`", "`11`, `12`"],
    explanation:
      "L'opérateur arithmétique `++` _renvoie en premier_ la valeur de l'opérande, _puis incrémente_ la valeur de l'opérande. La valeur de `num1` est égale à `10`, puisque la fonction `increaseNumber` renvoie d'abord la valeur de `num`, qui correspond à `10`, et augmente la valeur de `num` par la suite.\n\n`num2` est égal à `10`, puisque nous avons passé `num1` à la commande `increasePassedNumber`. `number` est égal à `10` (la valeur de `num1`). Encore une fois, l'opérateur arithmétique `++` _renvoie d'abord_ la valeur de l'opérande, puis incrémente_ la valeur de l'opérande. La valeur de `nombre` est `10`, donc `num2` est égal à `10`.",
    id: 63,
  },
  {
    grade: "Middle",
    theme: "Тонкости и неоднозначности языка",
    question: "Quelle est la sortie?",
    code: "const value = { number: 10 };\n\nconst multiply = (x = { ...value }) => {\n  console.log((x.number *= 2));\n};\n\nmultiply();\nmultiply();\nmultiply(value);\nmultiply(value);",
    correctAnswer: 3,
    variants: [
      "`20`, `40`, `80`, `160`",
      "`20`, `40`, `20`, `40`",
      "`20`, `20`, `20`, `40`",
      "`NaN`, `NaN`, `20`, `40`",
    ],
    explanation:
      "Dans ES6, nous pouvons initialiser les paramètres avec une valeur par défaut. La valeur du paramètre sera la valeur par défaut, si aucune autre valeur n'a été passée à la fonction, ou si la valeur du paramètre est `\"undefined\"`. Dans ce cas, nous répartissons les propriétés de l'objet `value` dans un nouvel objet, donc `x` a la valeur par défaut `{number: 10}`.\n\nL'argument par défaut est évalué at _call time_! Chaque fois que nous appelons la fonction, un a _new_ object  créé. Nous invoquons la fonction `multiply` les deux premières fois sans passer de valeur: `x` a la valeur par défaut `{number: 10}`. Nous enregistrons ensuite la valeur multipliée de ce nombre, qui est `20`.\n\nLa troisième fois que nous invoquons multiplier, nous passons un argument: l'objet appelé `value`. L'opérateur `* =` est en fait un raccourci pour `x.number = x.number * 2`: nous modifions la valeur de `x.number`, et enregistrons la valeur multipliée `20`.\n\nLa quatrième fois, nous passons à nouveau l'objet `value`. `x.number` a été précédemment modifié en `20`, donc `x.number * = 2` enregistre «40».",
    id: 64,
  },
];
export default questions;
