import { Grades, Themes } from "../../model";

const questions = [
  {
    grade: Grades.Junior,
    theme: Themes.DATA_TYPES,
    question: "Qual é a saída?",
    code: 'function sayHi() {\n  console.log(name);\n  console.log(age);\n  var name = "Lydia";\n  let age = 21;\n}\n\nsayHi();',
    correctAnswer: 4,
    variants: [
      "`Lydia` e `undefined`",
      "`Lydia` e `ReferenceError`",
      "`ReferenceError` e `21`",
      "`undefined` e `ReferenceError`",
    ],
    explanation:
      'Dentro da função, nós primeiro declaramos a variável `name` usando a palavra-chave `var`. Isso significa que a variavel é elevada(hoisted) (O espaço na memória é separado durante a fase de criação) com o valor padrão `undefined`, até que chegue na linha onde definimos a variável. Ainda não definimos a variável na linha onde tentamos usar colocar no log o valor da variável `name`, portanto ela ainda tem o valor `undefined`.\n\nVariáveis com a palavra-chave `let` (e `const`) são elevadas, mas diferente de `var`, não são _inicializadas_. Elas não estão acessíveis antes da linha em que as declaramos (ou inicializamos). Esse é um conceito chamado de "temporal dead zone". Quando tentamos acessar essas variáveis antes de serem declaradas, o JavaScript lança um `ReferenceError`.',
    id: 1,
  },
  {
    grade: Grades.Middle,
    theme: Themes.ASYNC,
    question: "Qual é a saída?",
    code: "for (var i = 0; i < 3; i++) {\n  setTimeout(() => console.log(i), 1);\n}\n\nfor (let i = 0; i < 3; i++) {\n  setTimeout(() => console.log(i), 1);\n}",
    correctAnswer: 3,
    variants: ["`0 1 2` e `0 1 2`", "`0 1 2` e `3 3 3`", "`3 3 3` e `0 1 2`"],
    explanation:
      "Por causa da fila de eventos em JavaScript, a callback de `setTimeout` é chamada _depois_ do laço ter sido executado. Já que a variável `i` no primeiro laço foi declarada usando a palavra-chave `var`, seu valor era global. Durante o laço, incrementamos o valor de `i` por `1` em cada repetição, usando o operador unário `++`. Quando a callback de `setTimeout` foi chamada, `i` valia `3`.\n\nNo segundo laço, a variável `i` foi declarada usando a palavra-chave `let`: Variáveis declaradas com `let` (e `const`) só são acessíveis nos escopos de seus blocos (um bloco é qualquer código entre `{ }`). Durante cada repetição do laço, `i` vai ter um novo valor, e cada valor tem seu escopo dentro do laço.",
    id: 2,
  },
  {
    grade: Grades.Junior,
    theme: Themes.OBJECTS,
    question: "Qual é a saída?",
    code: "const shape = {\n  radius: 10,\n  diameter() {\n    return this.radius * 2;\n  },\n  perimeter: () => 2 * Math.PI * this.radius\n};\n\nshape.diameter();\nshape.perimeter();",
    correctAnswer: 2,
    variants: [
      "`20` e `62.83185307179586`",
      "`20` e `NaN`",
      "`20` e `63`",
      "`NaN` e `63`",
    ],
    explanation:
      "Perceba que o valor de `diameter` é uma função normal, enquanto que o valor de `perimeter` é uma arrow function.\n\nCom arrow functions, a palavra-chave `this` faz referência ao escopo atual em que está inserida, diferente de funções normais! Isso significa que quando nós chamamos `perimeter`, ela não faz referência ao objeto _shape_, mas ao seu escopo atual (por exemplo, _window_).\n\nNão há `radius` fora de _shape_, então retorna `undefined`.",
    id: 3,
  },
  {
    grade: Grades.Middle,
    theme: Themes.DATA_TYPES,
    question: "Qual é a saída?",
    code: '+true;\n!"Lydia";',
    correctAnswer: 1,
    variants: ["`1` and `false`", "`false` and `NaN`", "`false` and `false`"],
    explanation:
      "O operador unário `+` tenta converter um operando para um número. `true` é `1`, e `false` é `0`.\n\nA string `'Lydia'` tem valor truthy*. O que estamos realmente perguntando é \"Esse valor truthy é falsy?\". Isso retorna `false`.  \n###### *Nota do tradutor: _truthy_ é um termo único ao JavaScript que denota valores que podem ser convertidos em um booleano `True`. Sua contraparte é _falsy_, que são valores que podem ser convertidos em um booleano `false`. Para fins de consistência, mantenho os termos originais.",
    id: 4,
  },
  {
    grade: Grades.Junior,
    theme: Themes.OBJECTS,
    question: "Qual é a alternativa correta?",
    code: 'const bird = {\n  size: "small"\n};\n\nconst mouse = {\n  name: "Mickey",\n  small: true\n};',
    correctAnswer: 1,
    variants: [
      "`mouse.bird.size` não é válido",
      "`mouse[bird.size]` não é válido",
      '`mouse[bird["size"]]` não é válido',
      "Todos são válidos",
    ],
    explanation:
      'No JavaScript, todas chaves dos objetos são strings (a não ser que sejam um símbolo). Ainda que não possamos _digitá-las_ como strings, elas são sempre convertidas para string sob o capô.\n\nJavaScript interpreta afirmações. Quando usamos a notação de colchetes, ele vê o colchete de abertura `[` e continua lendo até encontrar o colchete que o fecha `]`. Só então vai avaliar e rodar as afirmações.\n\n`mouse[bird.size]`: Primeiro avalia `bird.size`, que é `"small"`. `mouse["small"]` retorna `true`\n\nPor outro lado, com a notação de ponto `.`, isso não acontece. `mouse` não tem uma chave chamada `bird`, o que significa que `mouse.bird` é `undefined`. Então, pedimos pelo `size` usando a notação de ponto: `mouse.bird.size`. Uma vez que `mouse.bird` é `undefined`, estamos realmente pedindo `undefined.size`. Isso não é válido, e irá gerar um erro similar a `Cannot read property "size" of undefined`.',
    id: 5,
  },
  {
    grade: Grades.Junior,
    theme: Themes.OBJECTS,
    question: "Qual é a saída?",
    code: 'let c = { greeting: "Hey!" };\nlet d;\n\nd = c;\nc.greeting = "Hello";\nconsole.log(d.greeting);',
    correctAnswer: 1,
    variants: [
      "`Hello`",
      "`Hey`",
      "`undefined`",
      "`ReferenceError`",
      "`TypeError`",
    ],
    explanation:
      'Em JavaScript, todos objetos interagem por _referência_ quando os colocamos um igual ao outro.\n\nPrimeiro, a variável `c` guarda o valor de um objeto. Depois, declaramos `d` com a mesma referencia que `c` tem para o objeto.\n\n<img src="https://i.imgur.com/ko5k0fs.png" width="200">\n\nQuando você muda um objeto, você muda todos eles.',
    id: 6,
  },
  {
    grade: Grades.Middle,
    theme: Themes.DATA_TYPES,
    question: "Qual é a saída?",
    code: "let a = 3;\nlet b = new Number(3);\nlet c = 3;\n\nconsole.log(a == b);\nconsole.log(a === b);\nconsole.log(b === c);",
    correctAnswer: 3,
    variants: [
      "`true` `false` `true`",
      "`false` `false` `true`",
      "`true` `false` `false`",
      "`false` `true` `true`",
    ],
    explanation:
      "`new Number()` é uma funcção construtura padrão do JavaScript. Ainda que parece com um número, não é realmente um número: Tem um monte de funções extras e é um objeto.\n\nQuando usamos o operador `==`, só conferimos se ambas tem o mesmo _valor_. Ambas tem o valor de `3`, então retorna `true`. \n\nContudo, quando usamos o operador `===`, ambos valor _e_ tipo tem de ser o mesmo. E não são: `new Number()` não é um número, é um **objeto**. Ambos retornam `false`.",
    id: 7,
  },
  {
    grade: Grades.Middle,
    theme: Themes.CLASSES,
    question: "Qual é a saída?",
    code: 'class Chameleon {\n  static colorChange(newColor) {\n    this.newColor = newColor;\n    return this.newColor;\n  }\n\n  constructor({ newColor = "green" } = {}) {\n    this.newColor = newColor;\n  }\n}\n\nconst freddie = new Chameleon({ newColor: "purple" });\nfreddie.colorChange("orange");',
    correctAnswer: 4,
    variants: ["`orange`", "`purple`", "`green`", "`TypeError`"],
    explanation:
      "A função `colorChange` é estática. Métodos estáticos são designados para viver somente nos construtores em que são criados, e filhos não herdam esses métodos.\nJá que `freddie` é filho de `Chameleon`, a função não é herdada, e não está disponível para `freddie`: Um erro `TypeError` é gerado.",
    id: 8,
  },
  {
    grade: Grades.Junior,
    theme: Themes.OBJECTS,
    question: "Qual é a saída?",
    code: "let greeting;\ngreetign = {}; // Erro de digitação!\nconsole.log(greetign);",
    correctAnswer: 1,
    variants: [
      "`{}`",
      "`ReferenceError: greetign is not defined`",
      "`undefined`",
    ],
    explanation:
      'Cria o log do objeto, pois criamos um objeto vazio no objeto global! Quando erramos a digitação de `greeting` como `greetign`, o interpretador do JavaScript viu isso como `global.greetign = {}` (ou `window.greetign = {}` em um navegador).\n\nPara evitar esse comportamento, podemos usar `"use strict"`. Isso garante que você  tenha declarado uma variável antes de poder inicializá-la com algum valor.',
    id: 9,
  },
  {
    grade: Grades.Junior,
    theme: Themes.FUNCTIONS,
    question: "O que acontece quando fazemos isso?",
    code: 'function bark() {\n  console.log("Woof!");\n}\n\nbark.animal = "dog";',
    correctAnswer: 1,
    variants: [
      "Nada, isso é ok!",
      "`SyntaxError`. Não se pode adicionar propriedades em uma função dessa maneira.",
      "`undefined`",
      "`ReferenceError`",
    ],
    explanation:
      "Isso é possível em JavaScript, pois funções são objetos! (Tudo menos tipos primitivos são objetos)\n\nUma função é um tipo especial de objeto. O código que você escreve não é a verdadeira função. A função é um objeto com propriedades. E essa propriedade é invocável.",
    id: 10,
  },
  {
    grade: Grades.Junior,
    theme: Themes.CLASSES,
    question: "Qual é a saída?",
    code: 'function Person(firstName, lastName) {\n  this.firstName = firstName;\n  this.lastName = lastName;\n}\n\nconst member = new Person("Lydia", "Hallie");\nPerson.getFullName = function() {\n  return `${this.firstName} ${this.lastName}`;\n};\n\nconsole.log(member.getFullName());',
    correctAnswer: 1,
    variants: [
      "`TypeError`",
      "`SyntaxError`",
      "`Lydia Hallie`",
      "`undefined` `undefined`",
    ],
    explanation:
      "Você não pode adicionar propriedades para um construtor igual aos objetos normais. Se você quer adicionar uma funcionalidade para todos objetos ao mesmo tempo, você deve usar o prototype.\n\nEntão nesse caso\n\n```js\nPerson.prototype.getFullName = function() {\n  return `${this.firstName} ${this.lastName}`;\n};\n```\n\nfaria `member.getFullName()` funcionar. Por quê isso é beneficial? Digamos que tivéssemos esse método no próprio construtor. Talvez nem toda instância de `Person` precisasse desse método. Isso gastaria muita memória, uma vez que cada instância teria esse propriedade e teria seu espaço alocado. Ao invés disso, se adicionarmos somente ao protótipo, alocamos somente um único espaço na memória, e todas instâncias de `Person` ainda tem acesso ao método.",
    id: 11,
  },
  {
    grade: Grades.Junior,
    theme: Themes.CLASSES,
    question: "Qual é a saída?",
    code: 'function Person(firstName, lastName) {\n  this.firstName = firstName;\n  this.lastName = lastName;\n}\n\nconst lydia = new Person("Lydia", "Hallie");\nconst sarah = Person("Sarah", "Smith");\n\nconsole.log(lydia);\nconsole.log(sarah);',
    correctAnswer: 1,
    variants: [
      '`Person {firstName: "Lydia", lastName: "Hallie"}` e `undefined`',
      '`Person {firstName: "Lydia", lastName: "Hallie"}` e `Person {firstName: "Sarah", lastName: "Smith"}`',
      '`Person {firstName: "Lydia", lastName: "Hallie"}` e `{}`',
    ],
    explanation:
      "Na `sarah`, não usamos a palavra-chave `new`. Quando usamos `new`, se refere ao novo objeto vazio que criamos. Contudo, se não usarmos `new`, nos referimos ao **objeto global**!\n\nAfirmamos que `this.firstName` vale `\"Sarah\"` e `this.lastName` vale `\"Smith\"`. O que realmente fizemos foi definir `global.firstName = 'Sarah'` e `global.lastName = 'Smith'`. A `sarah` ainda é `undefined`.",
    id: 12,
  },
  {
    grade: Grades.Junior,
    theme: Themes.EVENTS,
    question: "Quais são as três fases na propagação de eventos?",
    code: null,
    correctAnswer: 4,
    variants: [
      "Target > Capturing > Bubbling",
      "Bubbling > Target > Capturing",
      "Target > Bubbling > Capturing",
      "Capturing > Target > Bubbling",
    ],
    explanation:
      'Durate a fase do **capturing**, o evento percorre os elementos pais até chegar no elemento algo. Isso alcança o elemento **target**, e o **bubbling** começa.\n ##### *Nota do tradutor: _bubbling_ descreve uma forma específica de propagação de eventos. Em tradução livre é "borbulhar", que indica como os eventos "sobem" a cadeia onde estão aninhados, mas prefiro por manter o original, visto que é o nome dessa forma de propagação.\n\n<img src="https://i.imgur.com/N18oRgd.png" width="200">',
    id: 13,
  },
  {
    grade: Grades.Junior,
    theme: Themes.CLASSES,
    question: "Todos objetos tem protótipos.",
    code: null,
    correctAnswer: 2,
    variants: ["Verdadeiro", "Falso"],
    explanation:
      "Todos objetos tem protótipos, exceto pelo **base object**. O base object tem acesso à alguns métodos e propriedades, como `.toString`. É o motivo de podermos usar métodos já embutidos no JavaScript! Todos métodos desse tipo já estão embutidos no protótipo. Apesar do JavaScript não encontrar algum método diretamente no seu objeto, ele percorre a cadeia de protótipos até encontrar no base, o que torna acessível para todo objeto.",
    id: 14,
  },
  {
    grade: Grades.Junior,
    theme: Themes.DATA_TYPES,
    question: "Qual é a saída?",
    code: 'function sum(a, b) {\n  return a + b;\n}\n\nsum(1, "2");',
    correctAnswer: 3,
    variants: ["`NaN`", "`TypeError`", '`"12"`', "`3`"],
    explanation:
      'JavaScript é uma **linguagem dinamicamente tipada**: Não especificamos quais tipos nossas variáveis são. Valores pode ser automaticamente convertidos em outro tipo sem você saber, o que é chamado de _coerção implicita de tipo_. **Coerção** é converter de um tipo em outro.\n\nNesse exemplo, JavaScript converte o número `1` em uma string, para que a função faça sentido e retorne um valor. Durante a adição de um tipo numérico (`1`) e uma string (`\'2\'`), o número é tratado como uma string. Podemos concatenar strings como `"Hello" + "World"`, então o que está acontecendo aqui é `"1" + "2"` que retorna `"12"`.',
    id: 15,
  },
  {
    grade: Grades.Junior,
    theme: Themes.BASICS,
    question: "Qual é a saída?",
    code: "let number = 0;\nconsole.log(number++);\nconsole.log(++number);\nconsole.log(number);",
    correctAnswer: 3,
    variants: ["`1` `1` `2`", "`1` `2` `2`", "`0` `2` `2`", "`0` `1` `2`"],
    explanation:
      "O operador unário no **sufixo**  `++`:\n\n1. Retorna o valor (retorna o valor `0`)\n2. Incrementa o valor (numero agora é `1`)\n\nO operador unário **prefixo** `++`:\n\n1. Incrementa o valor (numero agora é `2`)\n2. Retorna o valor (Retorna o valor `2`)\n\nIsso retorna `0 2 2`.",
    id: 16,
  },
  {
    grade: Grades.Junior,
    theme: Themes.FUNCTIONS,
    question: "Qual é a saída?",
    code: 'function getPersonInfo(one, two, three) {\n  console.log(one);\n  console.log(two);\n  console.log(three);\n}\n\nconst person = "Lydia";\nconst age = 21;\n\ngetPersonInfo`${person} is ${age} years old`;',
    correctAnswer: 2,
    variants: [
      '`"Lydia"` `21` `["", " is ", " years old"]`',
      '`["", " is ", " years old"]` `"Lydia"` `21`',
      '`"Lydia"` `["", " is ", " years old"]` `21`',
    ],
    explanation:
      "Se usamos template literals marcadas, ou tagged template literals, o valor do primeiro argumento é sempre um array com a string, separada pelos tagged template liberals. Os argumentos restantes recebem os valores das expressões passadas!",
    id: 17,
  },
  {
    grade: Grades.Junior,
    theme: Themes.OBJECTS,
    question: "Qual é a saída?",
    code: 'function checkAge(data) {\n  if (data === { age: 18 }) {\n    console.log("You are an adult!");\n  } else if (data == { age: 18 }) {\n    console.log("You are still an adult.");\n  } else {\n    console.log(`Hmm.. You don\'t have an age I guess`);\n  }\n}\n\ncheckAge({ age: 18 });',
    correctAnswer: 3,
    variants: [
      "`You are an adult!`",
      "`You are still an adult.`",
      "`Hmm.. You don't have an age I guess`",
    ],
    explanation:
      "Quando testamos igualdade, primitivos são comparados por seus _valores_, enquanto objetos são comparados por suas  _referências_. O JavaScript confere se os objetos tem a referência para o mesmo local na memória.\n\nOs dois objetos que estamos comparando não são assim: O objeto que passamos como parâmetro faz referência a uma posição na memória diferente daquela que o objeto que usamos para conferir a igualdade.\n\nÉ por isso que ambos `{ age: 18 } === { age: 18 }` E `{ age: 18 } == { age: 18 }` retornam `false`.",
    id: 18,
  },
  {
    grade: Grades.Junior,
    theme: Themes.FUNCTIONS,
    question: "Qual é a saída?",
    code: "function getAge(...args) {\n  console.log(typeof args);\n}\n\ngetAge(21);",
    correctAnswer: 3,
    variants: ['`"number"`', '`"array"`', '`"object"`', '`"NaN"`'],
    explanation:
      'O operador _spread_ (`...args`.) retorna um array com os argumentos. Um array é um objeto, então `typeof args` retorna `"object"`.',
    id: 19,
  },
  {
    grade: Grades.Junior,
    theme: Themes.BASICS,
    question: "Qual é a saída?",
    code: 'function getAge() {\n  "use strict";\n  age = 21;\n  console.log(age);\n}\n\ngetAge();',
    correctAnswer: 3,
    variants: ["`21`", "`undefined`", "`ReferenceError`", "`TypeError`"],
    explanation:
      'Com `"use strict"`, você pode ter certeza que não declarou variáveis globais. Nunca declaramos a variável `age`, e já que usamos `"use strict"`, ira gerar um erro de referência. Se não tivéssemos usado `"use strict"`, teria funcionado, uma vez que a propriedade `age` teria sido adicionada ao objeto global.',
    id: 20,
  },
  {
    grade: Grades.Junior,
    theme: Themes.BASICS,
    question: "Qual o valor de `sum`?",
    code: 'const sum = eval("10*10+5");',
    correctAnswer: 1,
    variants: ["`105`", '`"105"`', "`TypeError`", '`"10*10+5"`'],
    explanation:
      "`eval` executa o código mesmo se passado como string. Se é uma expressão, como nesse caso, ele calcula a expressão. A expressão é `10 * 10 + 5`. Isso retorna o número `105`.",
    id: 21,
  },
  {
    grade: Grades.Junior,
    theme: Themes.STORAGE,
    question: "Por quanto tempo cool_secret é acessível?",
    code: 'sessionStorage.setItem("cool_secret", 123);',
    correctAnswer: 2,
    variants: [
      "Sempre, o dado não é perdido.",
      "Quando o usuário fechar a guia.",
      "Quando o usuário fechar o navegador inteiro.",
      "Quando o usuário desligar o computador.",
    ],
    explanation:
      "Dados guardados em `sessionStorage` são removidos depois de fechar a _guia_.\n\nSe usássemos `localStorage`, o dado seria guardado para sempre, exceto se `localStorage.clear()` fosse chamado.",
    id: 22,
  },
  {
    grade: Grades.Junior,
    theme: Themes.BASICS,
    question: "Qual é a saída?",
    code: "var num = 8;\nvar num = 10;\n\nconsole.log(num);",
    correctAnswer: 2,
    variants: ["`8`", "`10`", "`SyntaxError`", "`ReferenceError`"],
    explanation:
      "Coma a palavra-chave `var`, você pode declarar várias variáveis com o mesmo nome. A variável vai guardar o último valor.\n\nVocê não pode fazer isso com `let` ou `const` uma vez que eles conferem o bloco de escopo em que estão inseridos.",
    id: 23,
  },
  {
    grade: Grades.Junior,
    theme: Themes.DATA_TYPES,
    question: "Qual é a saída?",
    code: 'const obj = { 1: "a", 2: "b", 3: "c" };\nconst set = new Set([1, 2, 3, 4, 5]);\n\nobj.hasOwnProperty("1");\nobj.hasOwnProperty(1);\nset.has("1");\nset.has(1);',
    correctAnswer: 3,
    variants: [
      "`false` `true` `false` `true`",
      "`false` `true` `true` `true`",
      "`true` `true` `false` `true`",
      "`true` `true` `true` `true`",
    ],
    explanation:
      "Todas as chaves de objetos (exceto símbolos) são strings debaixo do capô, mesmo que você não digite como uma string. É por isso que `obj.hasOwnProperty('1')` também retorna `true`.\n\nNão funciona assim para `Set`. Não tem um `'1'` no nosso set: `set.has('1')` retorna `false`. Temos o tipo número `1`, então `set.has(1)` retorna `true`.",
    id: 24,
  },
  {
    grade: Grades.Junior,
    theme: Themes.OBJECTS,
    question: "Qual é a saída?",
    code: 'const obj = { a: "one", b: "two", a: "three" };\nconsole.log(obj);',
    correctAnswer: 3,
    variants: [
      '`{ a: "one", b: "two" }`',
      '`{ b: "two", a: "three" }`',
      '`{ a: "three", b: "two" }`',
      "`SyntaxError`",
    ],
    explanation:
      "Se temos duas chaves com o mesmo nome, a última irá substituir a primeira. Ainda vai estar na primeira posição, mas com o último valor específicado.",
    id: 25,
  },
  {
    grade: Grades.Junior,
    theme: Themes.OBJECTS,
    question:
      "O contexto global de execução do JavaScript cria duas coisas para você: O objeto global, e a palavra-chave `this`.",
    code: null,
    correctAnswer: 1,
    variants: ["Verdadeiro", "Falso ", "Depende"],
    explanation:
      "O contexto base de execução é o contexto global: É aquilo que está acessível em qualquer lugar do código.",
    id: 26,
  },
  {
    grade: Grades.Junior,
    theme: Themes.BASICS,
    question: "Qual é a saída?",
    code: "for (let i = 1; i < 5; i++) {\n  if (i === 3) continue;\n  console.log(i);\n}",
    correctAnswer: 3,
    variants: ["`1` `2`", "`1` `2` `3`", "`1` `2` `4`", "`1` `3` `4`"],
    explanation:
      "A palavra-chave `continue` pula uma iteração se a condição retorna `true`.",
    id: 27,
  },
  {
    grade: Grades.Junior,
    theme: Themes.CLASSES,
    question: "Qual é a saída?",
    code: 'String.prototype.giveLydiaPizza = () => {\n  return "Just give Lydia pizza already!";\n};\n\nconst name = "Lydia";\n\nname.giveLydiaPizza();',
    correctAnswer: 1,
    variants: [
      '`"Just give Lydia pizza already!"`',
      "`TypeError: not a function`",
      "`SyntaxError`",
      "`undefined`",
    ],
    explanation:
      "`String` é um construtor embutido, no qual podemos adicionar propriedades. Nesse caso adicionamos um método ao seu protótipo. Tipos primitivos `string` são automaticamente convertidos em um objeto string, gerado pelo construtor `String`. Assim, todas as strings (que são objetos string) tem acesso ao método.",
    id: 28,
  },
  {
    grade: Grades.Middle,
    theme: Themes.DATA_TYPES,
    question: "Qual é a saída?",
    code: 'const a = {};\nconst b = { key: "b" };\nconst c = { key: "c" };\n\na[b] = 123;\na[c] = 456;\n\nconsole.log(a[b]);',
    correctAnswer: 2,
    variants: ["`123`", "`456`", "`undefined`", "`ReferenceError`"],
    explanation:
      'Chaves de objeto são automaticamente convertidas em strings. Estamos tentando usar um objeto como chave do objeto `a`, com o valor de `123`.\n\nContudo, quando transformamos um objeto em string, ele vira um `"[object Object]"`. Então, o que estamos afirmando é `a["object Object"] = 123`. Após, tentamos a mesma coisa. `c` é outro objeto que (implicitamente) convertemos para string. Então, temos `a["object Object"] = 456`.\n\nEntão, fazemos o log de `a[b]`, o que na verdade é `a["object Object"]`. Acabmos de definir esse valor, como `456`, e é isso que ele retorna.',
    id: 29,
  },
  {
    grade: Grades.Junior,
    theme: Themes.ASYNC,
    question: "Qual é a saída?",
    code: 'const foo = () => console.log("First");\nconst bar = () => setTimeout(() => console.log("Second"));\nconst baz = () => console.log("Third");\n\nbar();\nfoo();\nbaz();',
    correctAnswer: 2,
    variants: [
      "`First` `Second` `Third`",
      "`First` `Third` `Second`",
      "`Second` `First` `Third`",
      "`Second` `Third` `First`",
    ],
    explanation:
      'Temos a função `setTimeout` e a invocamos por primeiro. Ainda assim, apareceu no log por último.\n\nIsso acontece pois nos navegadores, não temos apenas o nosso mecanismo de execução (runtime engine), temos também algo chamado `WebAPI`. A `WebAPI` nos da coisas como a `setTimeout` e o DOM.\n\nDepois que a função de retorno (callback) é enviada para a `WebAPI`, a função `setTimeout` (mas não seu retorno ou callback) são enviadas para fora do stack.\n\n<img src="https://i.imgur.com/X5wsHOg.png" width="200">\n\nAgora, `foo` é chamada, e `"First"` é adicionado ao log.\n\n<img src="https://i.imgur.com/Pvc0dGq.png" width="200">\n\n`foo` é evniada para fora do stack, e `baz` é chamada. `"Third"` é adicionado ao log.\n\n<img src="https://i.imgur.com/WhA2bCP.png" width="200">\n\nA `WebAPI` não pode simplesmente adicionar coisas ao stack sempre que ficam prontas. Ao invés, disso, todo retorno que fica pronto é enviado para algo chamado _queue_.\n\n<img src="https://i.imgur.com/NSnDZmU.png" width="200">\n\nÉ aqui que um laço de evento começa a ocorrer. Um **laço de evento** confere o stack e o _queue_. Se o stack está livre, pega a primeira coisa que estiver na queue e coloca no stack.\n\n<img src="https://i.imgur.com/uyiScAI.png" width="200">\n\n`bar` é chamada, `"Second"` é adicionado ao log, e é enviado para fora do stack.',
    id: 30,
  },
  {
    grade: Grades.Junior,
    theme: Themes.EVENTS,
    question: "qual é o event.target quando clicamos no botão?",
    code: null,
    correctAnswer: 3,
    variants: [
      "A `div` mais externa",
      "A `div` mais interna",
      "`button`",
      "Um array dos elementos aninhandos.",
    ],
    explanation:
      "O elemento mais interno no aninhamento que causou o evento é o alvo do evento. Você pode parar o _bubbling_ com `event.stopPropagation`.",
    id: 31,
  },
  {
    grade: Grades.Junior,
    theme: Themes.EVENTS,
    question: "Quando você clica no parágrafo, O que é adicionado ao log?",
    code: null,
    correctAnswer: 1,
    variants: ["`p` `div`", "`div` `p`", "`p`", "`div`"],
    explanation:
      "Se clicarmos em `p`, veremos dois itens adicionaos ao log: `p` e `div`. Durante a propagação de eventos, existem 3 fases: capturar, adquirir o _target_, e o bubbling. Por padrão, manipuladores de eventos são executados junto a fase de bubbling (a não ser que você marque `useCapture` como `true`). Percorre do elemento aninhando mais interno, propagando para fora.",
    id: 32,
  },
  {
    grade: Grades.Junior,
    theme: Themes.FUNCTIONS,
    question: "Qual é a saída?",
    code: 'const person = { name: "Lydia" };\n\nfunction sayHi(age) {\n  console.log(`${this.name} is ${age}`);\n}\n\nsayHi.call(person, 21);\nsayHi.bind(person, 21);',
    correctAnswer: 4,
    variants: [
      "`undefined is 21` `Lydia is 21`",
      "`function` `function`",
      "`Lydia is 21` `Lydia is 21`",
      "`Lydia is 21` `function`",
    ],
    explanation:
      "Com ambos, podemos passar o objeto que queremos que o `this` faça referência. Contudo, `.call` é _executado imediatamente_!\n\n`.bind.` retorna uma _cópia_ da função, mas com seu contexto vinculado à cópia. E não é executado imediatamente.",
    id: 33,
  },
  {
    grade: Grades.Junior,
    theme: Themes.FUNCTIONS,
    question: "Qual é a saída?",
    code: "function sayHi() {\n  return (() => 0)();\n}\n\ntypeof sayHi();",
    correctAnswer: 2,
    variants: ['`"object"`', '`"number"`', '`"function"`', '`"undefined"`'],
    explanation:
      'A função `sayHi` retorna o valor retornado pela arrow function pois ela é uma IIFE (Immediately Invoked Function Expression ou Expressão de Função Invocada Imediatamente). Essa IIFE retornou `0`, que é do tipo `"number"`.\n\nPara saber mais: Só existem 7 tipos já definidos: `null`, `undefined`, `boolean`, `number`, `string`, `object`, `symbol`, e `bigint`. `"function"` não é um tipo, uma vez que  funções são objetos, elas são do tipo `"object"`.',
    id: 34,
  },
  {
    grade: Grades.Middle,
    theme: Themes.BASICS,
    question: "Qual desses tem valor falsy?",
    code: '0;\nnew Number(0);\n("");\n(" ");\nnew Boolean(false);\nundefined;',
    correctAnswer: 1,
    variants: [
      "`0`, `''`, `undefined`",
      "`0`, `new Number(0)`, `''`, `new Boolean(false)`, `undefined`",
      "`0`, `''`, `new Boolean(false)`, `undefined`",
      "Todos são falsy",
    ],
    explanation:
      "Existem somente seis valores falsy:\n\n- `undefined`\n- `null`\n- `NaN`\n- `0`\n- `''` (string vazia)\n- `false`\n\nFunções construtoras, como `new Number` e `new Boolean` são truthy.",
    id: 35,
  },
  {
    grade: Grades.Junior,
    theme: Themes.DATA_TYPES,
    question: "Qual é a sáida?",
    code: "console.log(typeof typeof 1);",
    correctAnswer: 2,
    variants: ['`"number"`', '`"string"`', '`"object"`', '`"undefined"`'],
    explanation:
      '`typeof 1` retorna `"number"`.\n`typeof "number"` retorna `"string"`',
    id: 36,
  },
  {
    grade: Grades.Junior,
    theme: Themes.BASICS,
    question: "Qual é a saída?",
    code: "const numbers = [1, 2, 3];\nnumbers[10] = 11;\nconsole.log(numbers);",
    correctAnswer: 3,
    variants: [
      "`[1, 2, 3, 7 x null, 11]`",
      "`[1, 2, 3, 11]`",
      "`[1, 2, 3, 7 x empty, 11]`",
      "`SyntaxError`",
    ],
    explanation:
      'Quando você define um valor para um elemento em um array que excede o tamanho do próprio array, o JavaScript cria algo chamado "empty slots" (espaços vazios). Na verdade, esses espaços vazios tem o valor de `undefined`, mas você verá algo como:\n\n`[1, 2, 3, 7 x empty, 11]`\n\ndependendo de onde você o executa, pois é diferente para cada navegador, node etc.',
    id: 37,
  },
  {
    grade: Grades.Middle,
    theme: Themes.FUNCTIONS,
    question: "Qual é a saída?",
    code: "(() => {\n  let x, y;\n  try {\n    throw new Error();\n  } catch (x) {\n    (x = 1), (y = 2);\n    console.log(x);\n  }\n  console.log(x);\n  console.log(y);\n})();",
    correctAnswer: 1,
    variants: [
      "`1` `undefined` `2`",
      "`undefined` `undefined` `undefined`",
      "`1` `1` `2`",
      "`1` `undefined` `undefined`",
    ],
    explanation:
      "O bloco do `catch` recebe o argumento `x`. Esse não é o mesmo `x` da variável de quando estamos passando os argumentos. A variável `x` é de escopo do seu bloco.\n\nDepois, definimos essa variável, dentro do seu bloco, para valor `1`, e definimos o valor de `y`, que pertence a um bloco maior. Agora, nos adicionamos ao log o valor de `x`, que dentro desse bloco tem valor `1`.\n\nFora do bloco do `catch`. `x` ainda é `undefined`, e `y` ainda é `2`. Quando tentamos usar `console.log(x)` fora do bloco do `catch`, isso retorna `undefined`, e `y` retorna `2`.",
    id: 38,
  },
  {
    grade: Grades.Junior,
    theme: Themes.DATA_TYPES,
    question: "Tudo em JavaScript ou é um...",
    code: null,
    correctAnswer: 1,
    variants: [
      "primitivo ou um objeto",
      "função ou um object",
      "Pegadinha! Somente objetos",
      "número ou um objeto",
    ],
    explanation:
      "JavaScript tem somente tipos primitivos e objetos.\n\nTipos primitivos são `boolean`, `null`, `undefined`, `bigint`, `number`, `string`, e `symbol`.\n\nO que diferencia um primitivo de um objeto é que primitivos não métodos ou propriedades. Contudo, se você está atento vai lembrar que `'foo'.toUpperCase()` retorna `'FOO'` e não resulta em um `TypeError`. Isso acontece pois quando você tenta acessar uma propriedade ou método em um primitivo como, por exemplo, uma string, JavaScript vai transformar esse primitivo em objeto usando um _wrapper_, nesse caso o `String`, e discarta o wrapper imediatamente após executar o método ou propriedade. Todos os primitivos, com exceção de `null` e `undefined` exibem esse comportamento.",
    id: 39,
  },
  {
    grade: Grades.Junior,
    theme: Themes.BASICS,
    question: "Qual é a saída?",
    code: "[[0, 1], [2, 3]].reduce(\n  (acc, cur) => {\n    return acc.concat(cur);\n  },\n  [1, 2]\n);",
    correctAnswer: 3,
    variants: [
      "`[0, 1, 2, 3, 1, 2]`",
      "`[6, 1, 2]`",
      "`[1, 2, 0, 1, 2, 3]`",
      "`[1, 2, 6]`",
    ],
    explanation:
      "`[1, 2]` é nosso valor inicial. É o valor que começamos, e portanto o valor do primeiro `acc`. Durante a primeira iteração, `acc` é `[1,2]`, e `cur` é `[0, 1]`. Nós concatemos ambos, o que resulta em `[1, 2, 0, 1]`.\n\nEntão, `[1, 2, 0, 1]` é `acc` e `[2, 3]` é o `cur`. Concatenamos novamente, e chegamos em `[1, 2, 0, 1, 2, 3]`.",
    id: 40,
  },
  {
    grade: Grades.Junior,
    theme: Themes.BASICS,
    question: "Qual é a saída?",
    code: '!!null;\n!!"";\n!!1;',
    correctAnswer: 2,
    variants: [
      "`false` `true` `false`",
      "`false` `false` `true`",
      "`false` `true` `true`",
      "`true` `true` `false`",
    ],
    explanation:
      '`null` é falsy. `!null` retorna `true`. `!true` retorna `false`.\n\n`""` é falsy. `!""` retorna `true`. `!true` retorna `false`.\n\n`1` é truthy. `!1` retorna `false`. `!false` retorna `true`.',
    id: 41,
  },
  {
    grade: Grades.Junior,
    theme: Themes.FUNCTIONS,
    question: "O que o método `setInterval` retorna no navegador?",
    code: 'setInterval(() => console.log("Hi"), 1000);',
    correctAnswer: 1,
    variants: [
      "um id único",
      "a quantidade de  millisegundos especificada",
      "a função passada",
      "`undefined`",
    ],
    explanation:
      "Retorna um id único. Esse id pode ser usado para limpar o intervalo com a função `clearInterval()`.",
    id: 42,
  },
  {
    grade: Grades.Junior,
    theme: Themes.DATA_TYPES,
    question: "Qual é o retorno?",
    code: '[..."Lydia"];',
    correctAnswer: 1,
    variants: [
      '`["L", "y", "d", "i", "a"]`',
      '`["Lydia"]`',
      '`[[], "Lydia"]`',
      '`[["L", "y", "d", "i", "a"]]`',
    ],
    explanation:
      "Strings são iteráveis. O operador do spread `...` mapeia todo caractére de um iterável para um elemento.",
    id: 43,
  },
  {
    grade: Grades.Junior,
    theme: Themes.ASYNC,
    question: "Qual é a saída?",
    code: "function* generator(i) {\n  yield i;\n  yield i * 2;\n}\n\nconst gen = generator(10);\n\nconsole.log(gen.next().value);\nconsole.log(gen.next().value);",
    correctAnswer: 3,
    variants: [
      "`[0, 10], [10, 20]`",
      "`20, 20`",
      "`10, 20`",
      "`0, 10 e 10, 20`",
    ],
    explanation:
      "Funções regulares não podem ser interrompidas durante execução após sua invocação. Entretanto, uma função generator pode ser interrompida, e depois continuar de onde parou. Uma função generator sempre possue a palavra chave `yield`, a função gera o valor específicado logo após. Note que a função generator, neste caso não retorna o valor, ele utiliza _yields_ no valor.\n\nPrimeiro, nós inicializamos a função generator com `i` igual a `10`. Nós chamamos a função generator utilizando o `next()` para próxima função. A primeira vez que executamos a função generator o `i` é igual a `10`. que possue a palavra chave `yield`: que atribue o yields ao valor de `i`. O generator é pausado e `10` é logado.\n\nEntão, chamamos a próxima função novamente com o `next()`. Que continua de onde foi interrompido anteirormente, ainda com `i` igual a `10`. Agora, ele encontra o próximo `yield`, e yields `i * 2`. `i` é igual a `10`, que então retorna `10 * 2`, que é `20`. Seu resultado é `10, 20`.",
    id: 44,
  },
  {
    grade: Grades.Junior,
    theme: Themes.FUNCTIONS,
    question: "Qual o retorno?",
    code: 'const firstPromise = new Promise((res, rej) => {\n  setTimeout(res, 500, "one");\n});\n\nconst secondPromise = new Promise((res, rej) => {\n  setTimeout(res, 100, "two");\n});\n\nPromise.race([firstPromise, secondPromise]).then(res => console.log(res));',
    correctAnswer: 2,
    variants: ['`"one"`', '`"two"`', '`"two" "one"`', '`"one" "two"`'],
    explanation:
      "Quando passamos múltiplas \"promises\" para a função `Promise.race`, ele resolve ou rejeita a primeira \"promise\". Para a função de `setTimeout`, nós passamos um tempo de 500ms para a primeira promise (`firstPromise`), e 100ms para a segunda promise (`secondPromise`). Isso significa que o `secondPromise` resolve primeiro com o valor de `'two'`. `res` que agora possui o valor `'two'`, que foi logado.",
    id: 45,
  },
  {
    grade: Grades.Junior,
    theme: Themes.OBJECTS,
    question: "Qual é a saída?",
    code: 'let person = { name: "Lydia" };\nconst members = [person];\nperson = null;\n\nconsole.log(members);',
    correctAnswer: 4,
    variants: ["`null`", "`[null]`", "`[{}]`", '`[{ name: "Lydia" }]`'],
    explanation:
      'Primeiro, declaramos a variável `person` com o valor de um objeto que possui o propriedade `name`.\n\n<img src="https://i.imgur.com/TML1MbS.png" width="200">\n\nEntão, declaramos a variável chamada `members`. Setamos o valor do primeiro elemento do array igual ao valor da variável `person`. Objetos interados por _referência_ quando ao defini-los iguais entre si. Quando você atribui uma referência de uma variável para outra, você faz uma _cópia_ de sua referência. (note que eles não possuem a _mesma_ referência!)\n\n<img src="https://i.imgur.com/FSG5K3F.png" width="300">\n\nEntão, setamos a variável `person` igual a `null`.\n\n<img src="https://i.imgur.com/sYjcsMT.png" width="300">\n\nEstamos apenas modificando o valor da variável `person`, e não o primeiro elemento do array, desde que o elemento tem uma diferente referência (copiada) de um objeto. O primeiro elemento de `members` ainda mantém sua referência com o objeto original. Quando logamos o array de `members`, o primeiro elemento ainda mantém o valor do objeto, que é logado.',
    id: 46,
  },
  {
    grade: Grades.Junior,
    theme: Themes.DATA_TYPES,
    question: "Qual é a saída?",
    code: 'const person = {\n  name: "Lydia",\n  age: 21\n};\n\nfor (const item in person) {\n  console.log(item);\n}',
    correctAnswer: 2,
    variants: [
      '`{ name: "Lydia" }, { age: 21 }`',
      '`"name", "age"`',
      '`"Lydia", 21`',
      '`["name", "Lydia"], ["age", 21]`',
    ],
    explanation:
      "Utilizando o loop `for-in`, podemos interar através das chaves do objeto, neste caso o `name` e `age`. Por baixo dos panos, chaves de objetos são strings (eles não são um símbolo). Em cada loop, setamos ao valor do `item` igual ao da chave atual, que se intera. Primeiro, `item` é igual ao `name`, e é logado. Então, `item` é igual a idade `age`, que é logado.",
    id: 47,
  },
  {
    grade: Grades.Junior,
    theme: Themes.BASICS,
    question: "Qual é a saída?",
    code: 'console.log(3 + 4 + "5");',
    correctAnswer: 2,
    variants: ['`"345"`', '`"75"`', "`12`", '`"12"`'],
    explanation:
      'Associatividade do operador é a ordem na qual o compilador avalia as expressões, ou esquerda-para-direita ou direita-para-esquerda. Isso apenas acontece se todos os operatores possuem a _mesma_ precedência. Apenas temos um tipo de operador: `+`. Para adição, a associatividade é esquerda-para-direita.\n\n`3 + 4` é avaliado primeiro. Seu resultado é o número `7`.\n\n`7 + \'5\'` resulta em `"75"` por causa da coerção. JavaScript converte o número `7` em string, veja a questão 15. Podemos concatenar duas strings com o operador de `+`. `"7" + "5"` resulta em `"75"`.',
    id: 48,
  },
  {
    grade: Grades.Junior,
    theme: Themes.DATA_TYPES,
    question: "Qual o retorno de `num`?",
    code: 'const num = parseInt("7*6", 10);',
    correctAnswer: 3,
    variants: ["`42`", '`"42"`', "`7`", "`NaN`"],
    explanation:
      'Apenas os primeiros números da string é retornado. Baseado no _radix_ (o segundo parametro na ordem especifica qual o tipo de número queremos atribuir o parse: base 10, hexadecimal, octal, binary, etc.), o `parseInt` checa se os caracteres na string são válidos. Depois de encontrar um caracter que não é um número válido no radix, ele interrompe o parse e ignora os seguintes caracteres.\n\n`*` não é um número válido. Ele apenas usa o parse no `"7"` em decimal `7`. `num` possui o valor `7`.',
    id: 49,
  },
  {
    grade: Grades.Junior,
    theme: Themes.DATA_TYPES,
    question: "Qual é a saída?",
    code: '[1, 2, 3].map(num => {\n  if (typeof num === "number") return;\n  return num * 2;\n});',
    correctAnswer: 3,
    variants: [
      "`[]`",
      "`[null, null, null]`",
      "`[undefined, undefined, undefined]`",
      "`[ 3 x empty ]`",
    ],
    explanation:
      'Quando mapeamos um array (map), o valor de `num` é igual ao elemento que está percorrendo. Neste caso, os elementos são números, então a condição do se (if) `typeof num === "number"` retorna `true`. A função map cria um novo array e insere os valores retornados da função.\n\nEntretanto, não se retorna o valor. Quando não se retorna um valor para a função, a função retorna `undefined`. Para cada elemento do array, o bloco de função é chamado, então para cada elemento é retornado `undefined`.',
    id: 50,
  },
  {
    grade: Grades.Junior,
    theme: Themes.OBJECTS,
    question: "Qual é a saída?",
    code: 'function getInfo(member, year) {\n  member.name = "Lydia";\n  year = "1998";\n}\nconst person = { name: "Sarah" };\nconst birthYear = "1997";\ngetInfo(person, birthYear);\nconsole.log(person, birthYear);',
    correctAnswer: 1,
    variants: [
      '`{ name: "Lydia" }, "1997"`',
      '`{ name: "Sarah" }, "1998"`',
      '`{ name: "Lydia" }, "1998"`',
      '`{ name: "Sarah" }, "1997"`',
    ],
    explanation:
      'Os argumentos são passados ​​por _valor_. Porém, se seu valor for um objeto, eles são passados ​​por _referência_. `birthYear` é passado por valor, já que é uma string, não um objeto. Quando passamos argumentos por valor, uma _cópia_ desse valor é criada (consulte a pergunta 46).\n\nA variável `birthYear` tem uma referência ao valor `"1997"`. O argumento `year` também tem uma referência ao valor `"1997"`, mas não é o mesmo valor de referência de `birthYear`. Quando atualizamos o valor de `year`, definindo ` year` igual a `"1998"`, estamos apenas atualizando o valor de `year`. `birthYear` ainda é igual a `"1997"`.\n\nO valor de `person` é um objeto. O argumento `member` possui uma referência (copiada) do _mesmo_ objeto . Quando modificamos uma propriedade do objeto que `member` tem referência, o valor de `person` também será modificado, pois ambos tem referência ao mesmo objeto. A propriedade `name` de `person` agora é igual ao valor `"Lydia"`.',
    id: 51,
  },
  {
    grade: Grades.Junior,
    theme: Themes.ERRORS,
    question: "Qual é a saída?",
    code: 'function greeting() {\n  throw "Hello world!";\n}\nfunction sayHi() {\n  try {\n    const data = greeting();\n    console.log("It worked!", data);\n  } catch (e) {\n    console.log("Oh no an error:", e);\n  }\n}\nsayHi();',
    correctAnswer: 4,
    variants: [
      "`It worked! Hello world!`",
      "`Oh no an error: undefined`",
      "`SyntaxError: can only throw Error objects`",
      "`Oh no an error: Hello world!`",
    ],
    explanation:
      "Com a declaração `throw`, podemos criar erros personalizados. Com esta declaração, você pode lançar exceções. Uma exceção pode ser uma <b>string</b>, um <b>número</b>, um <b>booleano</b> ou um <b>objeto</b>. Nesse caso, nossa exceção é a string `'Hello world!'`.\n\nCom a declaração `catch`, podemos especificar o que fazer se uma exceção for lançada no bloco `try`. Uma exceção foi lançada: a string `'Hello world'`. `e` agora é igual a essa string que registramos. Isso resulta em `'Oh no an error: Hello world!'`.",
    id: 52,
  },
  {
    grade: Grades.Junior,
    theme: Themes.FUNCTIONS,
    question: "Qual é a saída?",
    code: 'function Car() {\n  this.make = "Lamborghini";\n  return { make: "Maserati" };\n}\nconst myCar = new Car();\nconsole.log(myCar.make);',
    correctAnswer: 2,
    variants: [
      '`"Lamborghini"`',
      '`"Maserati"`',
      "`ReferenceError`",
      "`TypeError`",
    ],
    explanation:
      'Quando você retorna uma propriedade, o valor da propriedade é igual ao valor _retornado_, não ao valor _definido_ na função do construtor. Retornamos a string `"Maserati"`, então `myCar.make` é igual a `"Maserati"`.',
    id: 53,
  },
  {
    grade: Grades.Senior,
    theme: Themes.OBJECTS,
    question: "Qual é a saída?",
    code: "(() => {\n  let x = (y = 10);\n})();\nconsole.log(typeof x);\nconsole.log(typeof y);",
    correctAnswer: 1,
    variants: [
      '`"undefined", "number"`',
      '`"number", "number"`',
      '`"object", "number"`',
      '`"number", "undefined"`',
    ],
    explanation:
      '`let x = y = 10;` é na realidade uma abreviação de:\n\n``` js```\n\nQuando definimos `y` igual a `10`, adicionamos na verdade uma propriedade `y` ao objeto global (`window` no navegador, `global` no Node). Em um navegador, `window.y` agora é igual a `10`.\n\nEntão, declaramos uma variável `x` com o valor de `y`, que é `10`. As variáveis ​​declaradas com `let` tem _escopo definido no bloco_ ou seja, são definidas apenas dentro do bloco em que são declaradas, neste caso, _immediately-invoked function_ (IIFE). Quando usamos o operador `typeof`, o operando `x` não está definido: estamos tentando acessar `x` fora do bloco em que está declarado. Isso significa que `x` não está definido. Os valores que não foram atribuídos ou declarados a um valor são do tipo `"undefined"`. `console.log(typeof x)` retorna `"undefined"`.\n\nNo entanto, criamos uma variável global `y` ao definir `y` igual a `10`. Este valor está acessível em qualquer lugar do nosso código. `y` é definido e mantém um valor do tipo `"number"`. `console.log(typeof y)` retorna `"number"`.',
    id: 54,
  },
  {
    grade: Grades.Middle,
    theme: Themes.CLASSES,
    question: "Qual é a saída?",
    code: 'class Dog {\n  constructor(name) {\n    this.name = name;\n  }\n}\nDog.prototype.bark = function() {\n  console.log(`Woof I am ${this.name}`);\n};\nconst pet = new Dog("Mara");\npet.bark();\ndelete Dog.prototype.bark;\npet.bark();',
    correctAnswer: 1,
    variants: [
      '`"Woof I am Mara"`, `TypeError`',
      '`"Woof I am Mara"`, `"Woof I am Mara"`',
      '`"Woof I am Mara"`, `undefined`',
      "`TypeError`, `TypeError`",
    ],
    explanation:
      "Podemos excluir propriedades de objetos usando `delete`, também no prototype. Ao excluir uma propriedade no prototype, ela não está mais disponível na cadeia de prototypes. Nesse caso, a função `bark` não está mais disponível no prototype depois de `delete Dog.prototype.bark`, mas ainda tentamos acessá-lo.\n\nQuando tentamos invocar algo que não é uma função, um `TypeError` é lançado. Neste caso, `TypeError: pet.bark is not a function`, uma vez que `pet.bark` é `undefined`.",
    id: 55,
  },
  {
    grade: Grades.Junior,
    theme: Themes.DATA_TYPES,
    question: "Qual é a saída?",
    code: "const set = new Set([1, 1, 2, 3, 4]);\nconsole.log(set);",
    correctAnswer: 4,
    variants: [
      "`[1, 1, 2, 3, 4]`",
      "`[1, 2, 3, 4]`",
      "`{1, 1, 2, 3, 4}`",
      "`{1, 2, 3, 4}`",
    ],
    explanation:
      "O objeto `Set` é uma coleção de valores _exclusivos_ : um valor pode ocorrer apenas uma vez.\n\nPassamos o iterável `[1, 1, 2, 3, 4]` com um valor `1` duplicado. Como não podemos ter dois dos mesmos valores em um conjunto, um deles é removido. Isso resulta em `{1, 2, 3, 4}`.",
    id: 56,
  },
  {
    grade: Grades.Middle,
    theme: Themes.MODULES,
    question: "Qual é a saída?",
    code: "// counter.js\nlet counter = 10;\nexport default counter;",
    correctAnswer: 3,
    variants: ["`10`", "`11`", "`Error`", "`NaN`"],
    explanation:
      "Um módulo importado é _somente leitura_: você não pode modificar o módulo importado. Somente o módulo que os exporta pode alterar seu valor.\n\nQuando tentamos aumentar o valor de `myCounter`, recebemos um erro: `myCounter` é somente leitura e não pode ser modificado.",
    id: 57,
  },
  {
    grade: Grades.Junior,
    theme: Themes.OBJECTS,
    question: "Qual é a saída?",
    code: 'const name = "Lydia";\nage = 21;\nconsole.log(delete name);\nconsole.log(delete age);',
    correctAnswer: 1,
    variants: [
      "`false`, `true`",
      '`"Lydia"`, `21`',
      "`true`, `true`",
      "`undefined`, `undefined`",
    ],
    explanation:
      "O operador `delete` retorna um valor booleano: `true` em uma exclusão bem-sucedida, caso contrário, ele retorna `false`. No entanto, variáveis declaradas com `var`, `const` ou `let` não podem ser excluídas usando o operador `delete`.\n\nA variável `name` foi declarada com `const`, portanto sua exclusão não é bem-sucedida: `false` é retornado. Quando definimos `age` igual a `21`, na verdade adicionamos uma propriedade chamada `age` para o objeto global. Dessa forma, você pode excluir propriedades dos objetos, portanto `delete age` returns `true`.",
    id: 58,
  },
  {
    grade: Grades.Junior,
    theme: Themes.BASICS,
    question: "Qual é a saída?",
    code: "const numbers = [1, 2, 3, 4, 5];\nconst [y] = numbers;\nconsole.log(y);",
    correctAnswer: 3,
    variants: ["`[[1, 2, 3, 4, 5]]`", "`[1, 2, 3, 4, 5]`", "`1`", "`[1]`"],
    explanation:
      'Podemos descompactar valores de matrizes ou propriedades de objetos através da desestruturação. Por exemplo:\n\n``` js```\n\n<img src="https://i.imgur.com/ADFpVop.png" width="200">\n\nO valor de `a` agora é `1` e o valor de `b` agora é `2`. O que realmente fizemos na pergunta é:\n\n``` js```\n\n<img src="https://i.imgur.com/NzGkMNk.png" width="200">\n\nIsso significa que o valor de `y` é igual ao primeiro valor no array, que é o número `1`. Quando registramos no console `y`, `1` é retornado.',
    id: 59,
  },
  {
    grade: Grades.Junior,
    theme: Themes.DATA_TYPES,
    question: "Qual é a saída?",
    code: 'const user = { name: "Lydia", age: 21 };\nconst admin = { admin: true, ...user };\nconsole.log(admin);',
    correctAnswer: 2,
    variants: [
      '`{ admin: true, user: { name: "Lydia", age: 21 } }`',
      '`{ admin: true, name: "Lydia", age: 21 }`',
      '`{ admin: true, user: ["Lydia", 21] }`',
      "`{ admin: true }`",
    ],
    explanation:
      'É possível combinar objetos usando o operador o spread operator `...`. Ele permite criar cópias dos pares de um objeto e adicioná-las a outro objeto. Nesse caso, criamos cópias do objeto `user` e as adicionamos ao objeto `admin`. O objeto `admin` agora contém os pares de chave/valor copiados, o que resulta em `{ admin: true, name: "Lydia", age: 21 }`.',
    id: 60,
  },
  {
    grade: Grades.Junior,
    theme: Themes.OBJECTS,
    question: "Qual é saída?",
    code: 'const person = { name: "Lydia" };\n\nObject.defineProperty(person, "age", { value: 21 });\n\nconsole.log(person);\nconsole.log(Object.keys(person));',
    correctAnswer: 3,
    variants: [
      '`{ name: "Lydia", age: 21 }`, `["name", "age"]`',
      '`{ name: "Lydia", age: 21 }`, `["name"]`',
      '`{ name: "Lydia"}`, `["name", "age"]`',
      '`{ name: "Lydia"}`, `["age"]`',
    ],
    explanation:
      'om o método `defineProperty`, podemos adicionar novas propriedades a um objeto ou modificar propriedades já existentes. Quando adicionamos uma propriedade a um objeto usando o método `defineProperty`, ela é, por padrão, _não enumerável_. O método`Object.keys` retorna todos os nomes de uma propriedade _enumerável_  de um objeto. Nesse caso, apenas `"name"`.\n\nPropriedades adicionadas usando o método `defineProperty` são imutáveis por padrão. Você pode sobrepor esse comportamento usando as propriedade `writable`, `configurable` e `enumerable`. \nAssim, o método `defineProperty` dá a você muito mais controle sobre as propriedades que você está adicionando a um objeto.',
    id: 61,
  },
  {
    grade: Grades.Junior,
    theme: Themes.DATA_TYPES,
    question: "Qual é a saída?",
    code: 'const settings = {\n  username: "lydiahallie",\n  level: 19,\n  health: 90\n};\n\nconst data = JSON.stringify(settings, ["level", "health"]);\nconsole.log(data);',
    correctAnswer: 1,
    variants: [
      '`"{"level":19, "health":90}"`',
      '`"{"username": "lydiahallie"}"`',
      '`"["level", "health"]"`',
      '`"{"username": "lydiahallie", "level":19, "health":90}"`',
    ],
    explanation:
      'O segundo argumento de `JSON.stringify` é o _substituo_. O substituto pode ser uma função ou um array, e deixa você controlar o que deve ser "stringfied", isto é, ser usado pelo método `JSON.stringfy`.\n\nSe o substituto (replacer) for um _array_, apenas os nomes de propriedades incluídos no array serão adicionados à string JSON. Nesse caso, apenas as propriedades com os nomes `"level"` ed `"health"` são incluída, `"username"` é excluída. `data` agora é igual a `"{"level":19, "health":90}"`.\n\nSe o substituto (replacer) for uma _função_, essa função é chamada em c ada propriedade no objeto que está sendo "Stringfied". O valor retornado dessa função será o valor da propriedade quanto adicionado à string JSON. Se o valor for `undefined`, essa propriedade é excluída da string JSON.',
    id: 62,
  },
  {
    grade: Grades.Middle,
    theme: Themes.FUNCTIONS,
    question: "Qual é a saída?",
    code: "let num = 10;\n\nconst increaseNumber = () => num++;\nconst increasePassedNumber = number => number++;\n\nconst num1 = increaseNumber();\nconst num2 = increasePassedNumber(num1);\n\nconsole.log(num1);\nconsole.log(num2);",
    correctAnswer: 1,
    variants: ["`10`, `10`", "`10`, `11`", "`11`, `11`", "`11`, `12`"],
    explanation:
      "O operador unário `++` primeiro _retorna_ o valor do operando, depois _incrementa_ esse valor. O valor de `num1` é `10`, pois a função `increaseNumber` retorna primeiro o valor de` num`, que é `10`, e apenas incrementa o valor de `num` posteriormente.\n\n`num2` é `10`, já que passamos `num1` para o `increasePassedNumber`. `number` é igual a` 10` (o valor de `num1`. Novamente, o operador unário `++` primeiro _retorna_ o valor do operando, depois _aumenta_ esse valor. O valor de` number` é `10`, então `num2` é igual a `10`.",
    id: 63,
  },
  {
    grade: Grades.Junior,
    theme: Themes.DATA_TYPES,
    question: "Qual é a saída?",
    code: "const value = { number: 10 };\n\nconst multiply = (x = { ...value }) => {\n  console.log((x.number *= 2));\n};\n\nmultiply();\nmultiply();\nmultiply(value);\nmultiply(value);",
    correctAnswer: 3,
    variants: [
      "`20`, `40`, `80`, `160`",
      "`20`, `40`, `20`, `40`",
      "`20`, `20`, `20`, `40`",
      "`NaN`, `NaN`, `20`, `40`",
    ],
    explanation:
      'No ES6, podemos inicializar parâmetros com um valor padrão. O valor do parâmetro será o valor padrão, se nenhum outro valor tiver sido passado para a função ou se o valor do parâmetro for `"undefined"`. Nesse caso, espalhamos (spread) as propriedades do objeto `value` para um novo objeto, para que `x` tenha o valor padrão de `{number: 10}`.\n\nO argumento padrão é executado _a cada chamada_! Toda vez que chamamos a função, um _novo_ objeto é criado. Invocamos a função `multiply` as duas primeiras vezes sem passar um valor: `x` tem o valor padrão de `{number: 10}`. Em seguida, registramos (log) o valor multiplicado desse número, que é `20`.\n\nNa terceira vez que invocamos multiply, passamos um argumento: o objeto chamado `value`. O operador `*=` é na verdade uma abreviação de `x.number = x.number * 2`: modificamos o valor de `x.number` e registramos (log) o valor multiplicado `20`.\n\nNa quarta vez, passamos o objeto `value` novamente. `x.number` foi modificado anteriormente para `20`, então `x.number *= 2` registra `40`.',
    id: 64,
  },
  {
    grade: Grades.Middle,
    theme: Themes.DATA_TYPES,
    question: "Qual é a saída?",
    code: "[1, 2, 3, 4].reduce((x, y) => console.log(x, y));",
    correctAnswer: 4,
    variants: [
      "`1` `2` and `3` `3` and `6` `4`",
      "`1` `2` and `2` `3` and `3` `4`",
      "`1` `undefined` and `2` `undefined` and `3` `undefined` and `4` `undefined`",
      "`1` `2` and `undefined` `3` and `undefined` `4`",
    ],
    explanation:
      'O primeiro argumento que o método `reduce` recebe é o _acumulador_, `x` neste caso. O segundo argumento é o _valor atual_, `y`. Com o método `reduce`, executamos uma função de retorno de chamada (callback function) em todos os elementos da matriz, o que pode resultar em um único valor.\n\nNeste exemplo, não estamos retornando nenhum valor, estamos simplesmente registrando os valores do acumulador e o valor atual.\n\nO valor do acumulador é igual ao valor retornado anteriormente da função de retorno de chamada (callback function). Se você não passar o argumento opcional `initialValue` para o método `reduce`, o acumulador será igual ao primeiro elemento na primeira chamada.\n\nNa primeira chamada, o acumulador (`x`) é `1` e o valor atual (`y`) é `2`. Não retornamos da função de retorno de chamada, registramos o acumulador e o valor atual: `1` e` 2` são registrados.\n\nSe você não retornar um valor de uma função, ele retornará `undefined`. Na próxima chamada, o acumulador é "undefined" e o valor atual é "3". `undefined` e `3` são registrados.\n\nNa quarta chamada, novamente não retornamos nada da função de retorno de chamada. O acumulador é novamente `undefined` e o valor atual é `4`. `undefined` e `4` são registrados.',
    id: 65,
  },
  {
    grade: Grades.Junior,
    theme: Themes.CLASSES,
    question:
      "Com qual construtor podemos estender com sucesso a classe `Dog`?",
    code: "class Dog {\n  constructor(name) {\n    this.name = name;\n  }\n};\n\nclass Labrador extends Dog {\n  // 1\n  constructor(name, size) {\n    this.size = size;\n  }\n  // 2\n  constructor(name, size) {\n    super(name);\n    this.size = size;\n  }\n  // 3\n  constructor(size) {\n    super(name);\n    this.size = size;\n  }\n  // 4\n  constructor(name, size) {\n    this.name = name;\n    this.size = size;\n  }\n\n};",
    correctAnswer: 4,
    variants: ["1", "2", "3", "4"],
    explanation:
      "og`?\n\n``` js```\n\n- A: 1\n- B: 2\n- C: 3\n- D: 4\n\n<details><summary><b>Resposta</b></summary>\n<p>\n\n#### Resposta: B\n\nEm uma classe derivada, você não pode acessar a palavra-chave `this` antes de chamar `super`. Se você tentar fazer isso, ele lançará um erro de referência (ReferenceError): 1 e 4 lançará um erro de referência.\n\nCom a palavra-chave `super`, chamamos o construtor dessa classe pai com os argumentos fornecidos. O construtor do pai recebe o argumento `name`, portanto, precisamos passar `name` para `super`.\n\nA classe `Labrador` recebe dois argumentos, `name`, pois estende `Dog`, e `size` como uma propriedade extra na classe `Labrador`. Ambos precisam ser passados para a função construtora no `Labrador`, que é feita corretamente usando o construtor 2.",
    id: 66,
  },
  {
    grade: Grades.Middle,
    theme: Themes.MODULES,
    question: "Qual é a saída?",
    code: "// index.js\nconsole.log('running index.js');\nimport { sum } from './sum.js';\nconsole.log(sum(1, 2));\n\n// sum.js\nconsole.log('running sum.js');\nexport const sum = (a, b) => a + b;",
    correctAnswer: 2,
    variants: [
      "`running index.js`, `running sum.js`, `3`",
      "`running sum.js`, `running index.js`, `3`",
      "`running sum.js`, `3`, `running index.js`",
      "`running index.js`, `undefined`, `running sum.js`",
    ],
    explanation:
      "Com a palavra-chave `import`, todos os módulos importados são _pre-parsed_. Isso significa que os módulos importados são executados _primeiro_, o código no arquivo que importa o módulo é executado _depois_.\n\nEsta é uma diferença entre `require()` no CommonJS e `import`! Com `require()`, você pode carregar dependências sob demanda enquanto o código está sendo executado. Se tivéssemos usado `require` em vez de `import`, `running index.js`,` running sum.js`, `3` teriam sido registrados no console.",
    id: 67,
  },
  {
    grade: Grades.Middle,
    theme: Themes.DATA_TYPES,
    question: "Qual é a saída?",
    code: "console.log(Number(2) === Number(2));\nconsole.log(Boolean(false) === Boolean(false));\nconsole.log(Symbol('foo') === Symbol('foo'));",
    correctAnswer: 1,
    variants: [
      "`true`, `true`, `false`",
      "`false`, `true`, `false`",
      "`true`, `false`, `true`",
      "`true`, `true`, `true`",
    ],
    explanation:
      "Todo símbolo (Symbol) é totalmente único. O objetivo do argumento passado ao símbolo é fornecer uma descrição ao símbolo. O valor do símbolo não depende do argumento passado. Ao testarmos a igualdade, estamos criando dois símbolos totalmente novos: o primeiro `Symbol('foo')` e o segundo `Symbol('foo')`. Esses dois valores são únicos e não são iguais entre si, `Symbol('foo') === Symbol('foo')` retorna `false`.",
    id: 68,
  },
  {
    grade: Grades.Junior,
    theme: Themes.BASICS,
    question: "Qual é a saída?",
    code: "const name = 'Lydia Hallie';\nconsole.log(name.padStart(13));\nconsole.log(name.padStart(2));",
    correctAnswer: 3,
    variants: [
      '`"Lydia Hallie"`, `"Lydia Hallie"`',
      '`" Lydia Hallie"`, `" Lydia Hallie"` (`"[13x whitespace]Lydia Hallie"`, `"[2x whitespace]Lydia Hallie"`)',
      '`" Lydia Hallie"`, `"Lydia Hallie"` (`"[1x whitespace]Lydia Hallie"`, `"Lydia Hallie"`)',
      '`"Lydia Hallie"`, `"Lyd"`,',
    ],
    explanation:
      'Com o método `padStart`, podemos adicionar preenchimento (padding) ao início de uma string. O valor passado para esse método é o comprimento _total_ da string junto com o preenchimento. A string `"Lydia Hallie"` tem um comprimento de `12`. `name.padStart(13)` insere 1 espaço no início da string, porque 12 + 1 é 13.\n\nSe o argumento passado para o método `padStart` for menor que o comprimento da matriz, nenhum preenchimento será adicionado.',
    id: 69,
  },
  {
    grade: Grades.Junior,
    theme: Themes.DATA_TYPES,
    question: "Qual é a saída?",
    code: "console.log('🥑' + '💻');",
    correctAnswer: 1,
    variants: [
      '`"🥑💻"`',
      "`257548`",
      "A string containing their code points",
      "Error",
    ],
    explanation:
      'Com o operador `+`, você pode concatenar seqüências de caracteres (strings). Neste caso, estamos concatenando a string `"🥑"` com a string `"💻"`, resultando em `"🥑💻"`.',
    id: 70,
  },
  {
    grade: Grades.Middle,
    theme: Themes.ASYNC,
    question:
      "Como podemos registrar os valores comentados após a instrução console.log?",
    code: "function* iniciarJogo() {\n  const resposta = yield 'Você ama JavaScript?';\n  if (resposta !== 'Sim') {\n    return \"Uau... Acho que entramos aqui\";\n  }\n  return 'O JavaScript também ama você ❤️';\n}\n\nconst jogo = iniciarJogo();\nconsole.log(/* 1 */); // Você ama JavaScript?\nconsole.log(/* 2 */); // O JavaScript também ama você ❤️",
    correctAnswer: 3,
    variants: [
      '`jogo.next("Sim").value` and `jogo.next().value`',
      '`jogo.next.value("Sim")` and `jogo.next.value()`',
      '`jogo.next().value` and `jogo.next("Sim").value`',
      '`jogo.next.value()` and `jogo.next.value("Sim")`',
    ],
    explanation:
      'omo podemos registrar os valores comentados após a instrução console.log?\n\n``` js```\n\n- A: `jogo.next("Sim").value` and `jogo.next().value`\n- B: `jogo.next.value("Sim")` and `jogo.next.value()`\n- C: `jogo.next().value` and `jogo.next("Sim").value`\n- D: `jogo.next.value()` and `jogo.next.value("Sim")`\n\n<details><summary><b>Resposta</b></summary>\n<p>\n\n#### Resposta: C\n\nUma função geradora "pausa" a sua execução quando encontra a palavra-chave `yield`. Primeiro, temos que deixar a função produzir a string "Você ama JavaScript?", o que pode ser feito chamando `game.next().value`.\n\nCada linha é executada, até encontrar a primeira palavra-chave `yield`. Há uma palavra-chave `yield` na primeira linha da função: a execução para com o primeiro retorno! _Isso significa que a variável `resposta` ainda não foi definida!_\n\nQuando chamamos `game.next("Sim").value`, o `yield` anterior é substituído pelo valor dos parâmetros passados para a função `next()`, `"Sim"` neste caso. O valor da variável `"resposta"` agora é igual a `"Sim"`. A condição da instrução if retorna `false` e `JavaScript também ama você ❤️` é registrada.',
    id: 71,
  },
];
export default questions;
